import {MergeGame,VERSION,STEP,NAMES,RADII,FIELD} from './engine.mjs';
import * as rankings from './leaderboard.js';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');
const files=['meowth','eevee','squirtle','pikachu','psyduck','gengar','snorlax','jigglypuff'];
const pictures=files.map(()=>new Image()),keys=new Set();
let mode='speed',begun=false;
let game=new MergeGame(1,mode),ready=false,aim=240,paused=false,raf=0,last=0,accumulator=0,session=null,drops=[],demo=false,reported=false,starting=false,sparks=[];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let best=0;const bestKey=()=> 'jigglypuff-best-v3-'+mode;function loadBest(){best=0;try{best=Number(localStorage.getItem(bestKey()))||0;}catch{}$('best-label').textContent=mode==='speed'?'이 기기 최단 시간':'이 기기 최고 점수';$('local-best').textContent=best?(mode==='speed'?rankings.duration(best):best):'—';}loadBest();
files.forEach((file,i)=>{const el=document.createElement('div'),img=document.createElement('img'),text=document.createElement('span');img.src=`./sprites/${file}.svg`;img.alt=NAMES[i];text.textContent=`${i+1}. ${NAMES[i]}`;el.append(img,text);$('sequence').append(el);});
function face(g,x,y,r,level,angle=0,alpha=1){if(!ready)return;g.save();g.translate(x,y);g.rotate(angle);g.globalAlpha=alpha;g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(pictures[level],-r,-r,2*r,2*r);g.restore();}
function preview(){const c=$('next'),g=c.getContext('2d');g.clearRect(0,0,160,160);face(g,80,80,73,game.next);$('next-name').textContent=NAMES[game.next];}
function resize(){const dpr=Math.min(devicePixelRatio||1,3),w=canvas.clientWidth;canvas.width=Math.round(w*dpr);canvas.height=Math.round(w*550/480*dpr);draw();}
function draw(){const bg='#F7F6F2',bowl='#FFFFFF',rim='#D9D8D3';ctx.setTransform(canvas.width/480,0,0,canvas.height/550,0,0);ctx.clearRect(0,0,480,550);ctx.fillStyle=bg;ctx.fillRect(0,0,480,550);ctx.fillStyle=bowl;ctx.fillRect(28,103,424,419);ctx.beginPath();ctx.moveTo(28,104);ctx.lineTo(28,522);ctx.lineTo(452,522);ctx.lineTo(452,104);ctx.lineWidth=7;ctx.strokeStyle=rim;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.save();ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(35,132);ctx.lineTo(445,132);ctx.lineWidth=1.4;ctx.strokeStyle='#CC6674';ctx.stroke();ctx.restore();
 if(game.overflow>0){ctx.globalAlpha=Math.min(.3,game.overflow*.14);ctx.fillStyle='#f0889c';ctx.fillRect(28,123,424,18);ctx.globalAlpha=1;}
 if(!game.over){let landing=522-RADII[game.current];for(const b of game.balls){const dx=Math.abs(b.x-aim),sum=b.r+RADII[game.current];if(dx<sum)landing=Math.min(landing,b.y-Math.sqrt(sum*sum-dx*dx));}ctx.save();ctx.globalAlpha=.45;ctx.setLineDash([3,7]);ctx.strokeStyle=rim;ctx.beginPath();ctx.moveTo(aim,73+RADII[game.current]);ctx.lineTo(aim,Math.max(110,landing));ctx.stroke();ctx.restore();face(ctx,aim,73,RADII[game.current],game.current,0,game.cooldown>0?.4:1);}
 for(const b of game.balls)face(ctx,b.x,b.y,b.r,b.level,b.angle);
 for(const s of sparks){ctx.save();ctx.globalAlpha=s.life/.45;ctx.beginPath();ctx.arc(s.x,s.y,s.r+12+(1-s.life/.45)*24,0,Math.PI*2);ctx.strokeStyle='#13A89C';ctx.lineWidth=3;ctx.stroke();ctx.restore();}
 if(paused||game.over){ctx.fillStyle=bowl;ctx.globalAlpha=.94;ctx.fillRect(58,172,364,76);ctx.globalAlpha=1;ctx.fillStyle='#0D0D0D';ctx.textAlign='center';ctx.font='600 25px system-ui';ctx.fillText(paused?'일시정지':game.won?'푸린 완성!':'게임 종료',240,205);ctx.font='15px system-ui';ctx.fillText(game.won&&mode==='speed'?rankings.duration(game.result().durationMs):game.points+'점',240,231);}
}
function controls(){$('drop').disabled=!ready||game.over||paused||starting||game.cooldown>0;$('pause').disabled=!ready||game.over||starting;$('demo').disabled=starting;$('mode-speed').disabled=starting;$('mode-endless').disabled=starting;$('restart').disabled=starting;}
function updateLabels(){$('score').textContent=game.points;$('timer').textContent=mode==='speed'?rankings.duration(game.result().durationMs):rankings.duration(game.result().durationMs).split('.')[0];controls();}
function finish(){if(reported)return;reported=true;rankings.lock(false);const result=game.result();$('status').textContent=(game.won?'푸린 완성!':'게임 종료')+` · ${mode==='speed'&&result.won?rankings.duration(result.durationMs):result.score+'점'}`+(demo?' · 합성 예시':'');if(!demo&&((mode==='speed'&&result.won&&(!best||result.durationMs<best))||(mode==='endless'&&result.score>best))){best=mode==='speed'?result.durationMs:result.score;try{localStorage.setItem(bestKey(),String(best));}catch{}loadBest();}if(session&&drops.length){const completed=session,replay={version:VERSION,ticks:game.ticks,drops:drops.map(a=>[...a])};session=null;rankings.submit(completed,replay);}else if(session){session=null;$('submission').textContent='낙하 기록이 없어 이번 경기는 등록하지 않았어요.';}}
function frame(ts){const dt=last?Math.min((ts-last)/1000,.05):0;last=ts;if(!paused){if(keys.has('ArrowLeft'))aimAt(aim-240*dt);if(keys.has('ArrowRight'))aimAt(aim+240*dt);}if(!paused&&begun){accumulator+=dt;while(accumulator>=STEP&&!game.over){game.step();for(const e of game.events){sparks.push({...e,life:.45});$('status').textContent=e.type==='clear'?'푸린 두 개! +1,280점':NAMES[e.level]+' 합성!';}game.events.length=0;accumulator-=STEP;}sparks=sparks.filter(s=>(s.life-=dt)>0);if(game.over)finish();}updateLabels();draw();raf=!paused&&(!game.over||sparks.length)?requestAnimationFrame(frame):0;}
function wake(){if(!raf){last=0;raf=requestAnimationFrame(frame);}}
function aimAt(x){aim=clamp(x,FIELD.left+RADII[game.current],FIELD.right-RADII[game.current]);}
function drop(){if(!ready||starting||paused||game.over)return;const x=Math.round(aim);if(game.drop(x)){begun=true;drops.push([game.ticks,x]);aimAt(aim);preview();controls();$('status').textContent='같은 얼굴을 붙여보세요.';wake();}}
function reset(seed=crypto.getRandomValues(new Uint32Array(1))[0],ranked=null){cancelAnimationFrame(raf);raf=0;game=new MergeGame(seed,mode);begun=false;session=ranked;drops=[];demo=false;reported=false;paused=false;accumulator=0;sparks=[];aim=240;keys.clear();$('pause').textContent='일시정지';$('mode-label').textContent=ranked?'회원 랭킹':'연습';loadBest();$('status').textContent='첫 낙하부터 시작 · 위치를 고르고 클릭하세요.';rankings.lock(!!ranked);preview();updateLabels();draw();wake();}
function togglePause(){if(game.over||starting)return;paused=!paused;keys.clear();$('pause').textContent=paused?'계속하기':'일시정지';cancelAnimationFrame(raf);raf=0;controls();draw();if(!paused)wake();}
function pointer(e){const r=canvas.getBoundingClientRect();aimAt((e.clientX-r.left)/r.width*480);}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{e.preventDefault();pointer(e);canvas.focus({preventScroll:true});drop();});
$('drop').addEventListener('click',()=>{drop();canvas.focus({preventScroll:true});});$('restart').addEventListener('click',()=>{reset();canvas.focus({preventScroll:true});});$('pause').addEventListener('click',()=>{togglePause();canvas.focus({preventScroll:true});});
$('demo').addEventListener('click',()=>{reset();demo=true;begun=true;$('mode-label').textContent='합성 예시 · 랭킹 제외';game.balls=mode==='speed'?[game.make(2,75,493),game.make(4,386,478),game.make(5,126,468),game.make(6,258,456),game.make(6,258,224)]:[game.make(7,240,430),game.make(7,240,244)];game.balls.forEach(b=>b.age=2);game.cooldown=240;$('status').textContent=mode==='speed'?'잠만보 + 잠만보 → 푸린':'푸린 + 푸린 → 1,280점 · 계속 진행';});
$('rank-start').addEventListener('click',async()=>{if(!ready||starting)return;if(!paused&&!game.over)togglePause();starting=true;rankings.lock(true);controls();try{const s=await rankings.prepare();reset(s.seed,s);canvas.focus({preventScroll:true});}catch(e){$('submission').textContent=e.message;rankings.lock(false);}finally{starting=false;controls();}});
for(const [id,key] of [['left','ArrowLeft'],['right','ArrowRight']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);aimAt(aim+(key==='ArrowLeft'?-24:24));draw();keys.add(key);});['pointerup','pointercancel','lostpointercapture'].forEach(event=>b.addEventListener(event,()=>keys.delete(key)));b.addEventListener('click',e=>{if(e.detail===0){aimAt(aim+(key==='ArrowLeft'?-24:24));draw();}});}
canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space','KeyP','Escape'].includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.repeat&&e.code==='Space')drop();if(!e.repeat&&['KeyP','Escape'].includes(e.code))togglePause();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(ready&&!paused&&!game.over)togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready&&!paused&&!game.over)togglePause();});
for(const selected of ['speed','endless'])$('mode-'+selected).addEventListener('click',()=>{if(starting||mode===selected)return;mode=selected;$('mode-speed').setAttribute('aria-pressed',String(mode==='speed'));$('mode-endless').setAttribute('aria-pressed',String(mode==='endless'));$('game-title').textContent=mode==='speed'?'푸린 만들기':'무한 만들기';$('game-description').textContent=mode==='speed'?'푸린을 완성하는 가장 빠른 기록에 도전하세요.':'계속 합성하며 최고 점수를 쌓아보세요.';$('mode-rule').textContent=mode==='speed'?'첫 낙하부터 시간 측정 · 푸린을 완성하면 종료 · 완성 기록만 랭킹 등록':'시간제한 없음 · 푸린 두 개는 사라지며 +1,280점 · 한계선을 넘을 때까지';$('goal-label').textContent=mode==='speed'?'최종 목표':'두 개면 보너스';rankings.setMode(mode);reset();});
new ResizeObserver(resize).observe(canvas);rankings.init();
Promise.all(pictures.map((img,i)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('이미지 로딩 시간이 초과됐어요. 새로고침해 주세요.')),12000);img.onload=()=>{clearTimeout(timer);resolve();};img.onerror=()=>{clearTimeout(timer);reject(Error('이미지를 불러오지 못했어요. 새로고침해 주세요.'));};img.src=`./sprites/${files[i]}.svg`;}))).then(()=>{ready=true;reset();resize();}).catch(e=>{$('status').textContent=e.message;});
