import {VERSION,NAMES} from './engine.mjs';
const $=id=>document.getElementById(id);let user=false,available=false,locked=false,pending=null,saving=false,generation=0,mode='speed';
export const duration=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;
async function api(body){const r=await fetch('/api/games/jigglypuff?mode='+mode,{credentials:'same-origin',signal:AbortSignal.timeout(15000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw Error('랭킹 서버에 연결할 수 없어요.');}if(!r.ok||!data.ok)throw Error(data.message||'기록을 불러오지 못했어요.');return data;}
function controls(){const disabled=locked||!user||!available||!!pending;$('rank-start').disabled=disabled;$('nickname').disabled=disabled;}
export function setMode(value){mode=value;$('rank-rule').textContent=mode==='speed'?'완성 시간 TOP 20 · 빠른 순':'최고 점수 TOP 20 · 동점이면 빠른 기록 순';$('rank-primary').textContent=mode==='speed'?'시간':'점수';$('rank-secondary').textContent=mode==='speed'?'점수':'시간';$('rank-body').replaceChildren();$('my-rank').textContent='';refresh();}
export function lock(value){locked=value;controls();}
export async function refresh(){const g=++generation;$('rank-status').textContent='순위를 불러오는 중…';try{const data=await api();if(g!==generation)return;user=data.loggedIn;available=true;$('auth-status').textContent=user?'공개 닉네임으로 회원 순위에 기록돼요.':'로그인하면 회원 랭킹에 등록돼요. 연습 게임은 바로 즐길 수 있어요.';$('login').hidden=user;$('rank-body').replaceChildren();for(const r of data.rows){const row=document.createElement('tr');if(r.is_me)row.className='is-me';for(const value of [r.rank,r.nickname+(r.is_me?' (나)':''),...(mode==='speed'?[duration(r.duration_ms),r.score]:[r.score,duration(r.duration_ms)])]){const td=document.createElement('td');td.textContent=value;row.append(td);}$('rank-body').append(row);}$('rank-status').textContent=data.rows.length?'':'아직 등록된 기록이 없어요.';$('my-rank').textContent=data.mine?`내 최고 · ${data.mine.rank}위 · ${mode==='speed'?duration(data.mine.duration_ms):data.mine.score+'점'}`:user?'아직 내 랭킹 기록이 없어요.':'';}catch(e){if(g!==generation)return;available=false;$('rank-status').textContent=e.message;$('auth-status').textContent='랭킹 연결 전에는 연습 게임으로 플레이할 수 있어요.';}controls();}
export async function prepare(){if(pending)throw Error('이전 기록을 등록하거나 등록을 포기해 주세요.');const nickname=$('nickname').value;const data=await api({action:'start',version:VERSION,nickname,mode});try{localStorage.setItem('jigglypuff-nickname',nickname);}catch{}$('submission').textContent='랭킹 경기 · 종료 후 자동 등록';return data;}
async function send(){if(!pending||saving)return;saving=true;$('retry').disabled=true;$('discard').disabled=true;$('submission').textContent='플레이를 검증하고 등록하는 중…';try{const response=await api(pending);pending=null;$('submission').textContent=response.ranked===false?'푸린을 완성하지 못해 시간 랭킹에는 등록되지 않았어요.':'등록 완료! 더 좋은 기록이면 내 최고 기록이 갱신돼요.';$('retry').hidden=true;$('discard').hidden=true;await refresh();}catch(e){$('submission').textContent='등록 실패 · '+e.message;$('retry').hidden=false;$('discard').hidden=false;}finally{saving=false;$('retry').disabled=false;$('discard').disabled=false;controls();}}
export async function submit(session,replay){if(!session)return;pending={action:'finish',sessionId:session.sessionId,replay};controls();await send();}
export function init(){try{$('nickname').value=localStorage.getItem('jigglypuff-nickname')||'';}catch{}$('refresh').addEventListener('click',refresh);$('retry').addEventListener('click',send);$('discard').addEventListener('click',()=>{pending=null;$('retry').hidden=true;$('discard').hidden=true;$('submission').textContent='이번 기록의 등록을 포기했어요.';controls();});refresh();}
