import {maxHP} from './core.mjs';
import {entity} from './i18n.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const atCamp=g=>{const p=g.compositions?.regions[g.save.region]?.safePoint.position;return !!p&&!!g.player&&Math.hypot(g.player.model.position.x-p.x,g.player.model.position.z-p.z)<10;};
export async function swapCamp(game,slot,incomingUid,expectedUid){if(game.partnerChanging||game.restoring||game.survivalDying||game.transitioning||game.capture||game.phase!=='playing'||!atCamp(game))return false;if(!Number.isInteger(slot)||slot<0||slot>Math.min(5,game.save.party.length)||game.save.party[slot]!==expectedUid||game.save.party.includes(incomingUid))return false;const p=game.save.collection.find(p=>p.uid===incomingUid);if(!p||(slot===0&&p.hp<=0)||game.wild.some(a=>a.hp>0&&(a.boss||a.angry)&&a.model.position.distanceTo(game.player.model.position)<26))return false;game.partnerChanging=true;const epoch=game.regionEpoch,save=game.save,oldPlayer=game.player,before=[...save.party];let model;
 try{game.syncPlayer();if(slot===0)model=await game.resources.create(p.id,{shiny:p.shiny,scale:1.3,maxDimension:5});if(game.restoring||game.regionEpoch!==epoch||game.save!==save){model?.userData.release();return false;}const party=[...before];party[slot]=incomingUid;save.party=party;if(slot===0){await game.createPlayer([oldPlayer.model.position.x,oldPlayer.model.position.z],model);oldPlayer.model.userData.release();}game.campSelection=null;game.persist();game.emit('movesChanged');game.emit('refreshPanel');return true;}catch(error){save.party=before;game.player=oldPlayer;model?.userData.release();game.notify('친구 교체 실패','명단을 그대로 유지했어요. '+error.message,true);return false;}finally{game.partnerChanging=false;}}
export function renderCamp(ui){const g=ui.game,host=document.querySelector('#camp-manager');if(!host)return;const choose=ui.campChoice??={slot:null,uid:null},party=g.save.party,friend=uid=>g.save.collection.find(p=>p.uid===uid),card=p=>{if(!p)return '<span>빈 파트너 자리</span>';const s=g.byId.get(p.id);return `<b>${esc(s.name)} ${p.shiny?'✦ 이로치':''}</b><small>레벨 ${p.level} · 체력 ${Math.ceil(p.hp)} / ${maxHP(s,p.level)}</small><small>${s.types.map(t=>entity('types',t)).join(' / ')} · ${p.status?entity('statuses',p.status,p.status):'정상'}</small>`;};
 const query=(ui.campSearch||'').trim().toLocaleLowerCase(),sort=ui.campSort||'recent';let stored=g.save.collection.filter(p=>!party.includes(p.uid)&&g.byId.get(p.id).name.toLocaleLowerCase().includes(query));stored=stored.map((p,i)=>({p,i})).sort((a,b)=>sort==='level'?b.p.level-a.p.level||a.i-b.i:sort==='name'?g.byId.get(a.p.id).name.localeCompare(g.byId.get(b.p.id).name,'ko')||a.i-b.i:b.i-a.i).map(x=>x.p);
 const outgoing=choose.slot===null?null:friend(party[choose.slot]),incoming=friend(choose.uid),valid=choose.slot!==null&&incoming&&!party.includes(incoming.uid)&&atCamp(g)&&!(choose.slot===0&&incoming.hp<=0);
 host.innerHTML=`<h3>함께 다니는 파트너</h3><p class="notice">① 바꿀 자리 선택 → ② 캠프 친구 선택 → ③ 비교 후 적용. 교체로 체력·허기·갈증은 회복되지 않아요.</p><div class="camp-slots">${Array.from({length:Math.min(6,party.length+1)},(_,i)=>`<button data-camp-slot="${i}" class="${choose.slot===i?'selected':''}"><span>${i===0?'현재 필드 파트너':(i+1)+'번 자리'}</span>${card(friend(party[i]))}</button>`).join('')}</div><h3>캠프에서 쉬는 친구들</h3><div class="camp-filter"><input id="camp-search" aria-label="캠프 친구 이름 검색" placeholder="친구 이름 검색" value="${esc(ui.campSearch||'')}"><select id="camp-sort" aria-label="캠프 친구 정렬"><option value="recent">최근 합류순</option><option value="name">이름순</option><option value="level">레벨 높은순</option></select></div><div class="camp-friends">${stored.map(p=>`<button data-camp-friend="${esc(p.uid)}" class="${choose.uid===p.uid?'selected':''}">${card(p)}</button>`).join('')||'<p class="notice">조건에 맞는 캠프 친구가 없어요.</p>'}</div>${incoming&&choose.slot!==null?`<div class="camp-comparison"><article><small>파트너 → 캠프</small>${card(outgoing)}</article><span>⇄</span><article><small>캠프 → ${choose.slot===0?'필드 파트너':(choose.slot+1)+'번 자리'}</small>${card(incoming)}</article></div>`:''}<p class="notice">${atCamp(g)?'다친 친구의 실제 회복은 쉼터의 쉬기를 이용하세요.':'친구 교체는 지역의 안전한 캠프에서 할 수 있어요.'}</p><div class="pause-actions"><button id="camp-apply" ${valid?'':'disabled'}>이 명단으로 교체</button><button id="camp-cancel">선택 취소</button></div>`;
 host.querySelector('#camp-sort').value=sort;host.querySelectorAll('[data-camp-slot]').forEach(b=>b.onclick=()=>{choose.slot=Number(b.dataset.campSlot);choose.expectedUid=party[choose.slot];renderCamp(ui);});host.querySelectorAll('[data-camp-friend]').forEach(b=>b.onclick=()=>{choose.uid=b.dataset.campFriend;renderCamp(ui);});host.querySelector('#camp-search').oninput=e=>{const start=e.target.selectionStart;ui.campSearch=e.target.value;renderCamp(ui);const input=host.querySelector('#camp-search');input.focus();input.setSelectionRange(start,start);};host.querySelector('#camp-sort').onchange=e=>{ui.campSort=e.target.value;renderCamp(ui);};host.querySelector('#camp-cancel').onclick=()=>{ui.campChoice=null;renderCamp(ui);};host.querySelector('#camp-apply').onclick=async e=>{e.target.disabled=true;const ok=await swapCamp(g,choose.slot,choose.uid,choose.expectedUid);if(ok)ui.campChoice=null;else g.notify('교체할 수 없어요','캠프 위치·전투 상태·필드 파트너의 체력을 확인하세요.');renderCamp(ui);};
}
