import {SAVE_KEY,LEGACY_SAVE_KEY,parseSave,serialize,maxHP} from './core.mjs';
import {migrateFiveSave} from './save-migration.mjs';
export const memoryStorage=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)};};
export const owner=save=>save.collection[0]?.uid;
export const checkpointKey=save=>SAVE_KEY+':checkpoint:'+owner(save);
const digest=text=>{let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return (h>>>0).toString(16);};
export function validateRecord(text,game){const r=JSON.parse(text);if(r?.schema!==1||r.owner!==owner(game.save)||typeof r.snapshot!=='string'||r.checksum!==digest(r.snapshot)||!Number.isFinite(Date.parse(r.savedAt)))throw Error('복귀 기록이 손상되었거나 다른 탐험의 기록이에요.');const s=migrateFiveSave(r.snapshot,game.compositions),region=game.compositions.regions[s.region],p=s.collection.find(p=>p.uid===s.party[0]);if(!region||!p||p.hp<maxHP(game.byId.get(p.id),p.level)*.25||p.status||s.survival.hunger<25||s.survival.thirst<25||owner(s)!==r.owner||!Number.isFinite(s.playTime)||s.playTime<0)throw Error('안전하지 않은 복귀 기록이에요.');const q=region.safePoint.position;if(Math.hypot(s.position[0]-q.x,s.position[1]-q.z)>10)throw Error('저장 장소를 확인할 수 없어요.');return {...r,save:s};}
export function makeRecord(game,save,kind='manual'){const snapshot=serialize(save),r={schema:1,owner:owner(save),kind,region:save.region,place:game.biomeById.get(save.region).name,savedAt:new Date().toISOString(),snapshot,checksum:digest(snapshot)};validateRecord(JSON.stringify(r),game);return r;}
export function archiveOriginal(game){const storage=game.storage||globalThis.localStorage,tag=SAVE_KEY+':before-checkpoints:'+owner(game.save);for(const key of [SAVE_KEY,SAVE_KEY+':backup',LEGACY_SAVE_KEY,LEGACY_SAVE_KEY+':backup']){const value=storage.getItem(key);if(value&&!storage.getItem(tag+':'+key))storage.setItem(tag+':'+key,value);}game.resumeWritesBlocked=false;}
export function archiveSupplyOriginal(game){if(game.suppliesArchiveReady===owner(game.save)||!game.save.starter)return;const storage=game.storage||globalThis.localStorage,tag=SAVE_KEY+':before-supplies:'+owner(game.save);for(const key of [SAVE_KEY,SAVE_KEY+':backup',LEGACY_SAVE_KEY,LEGACY_SAVE_KEY+':backup',checkpointKey(game.save)]){const raw=storage.getItem(key);if(raw!==null&&storage.getItem(tag+':'+key)===null)storage.setItem(tag+':'+key,raw);}game.suppliesArchiveReady=owner(game.save);}
export function initializeCheckpoint(game){if(!game.save.starter)return;try{archiveSupplyOriginal(game);}catch(error){game.notify('기존 저장 원본을 보존하지 못했어요','저장 공간을 확보하기 전까지 새 기록 쓰기를 보류해요.',true);}const storage=game.storage||globalThis.localStorage,key=checkpointKey(game.save);let raw=null;try{raw=storage.getItem(key);}catch(error){game.notify('브라우저 저장소를 읽지 못했어요','이번 실행의 안전 복귀 기록은 메모리에 유지해요.',true);}if(raw){try{game.checkpoint=validateRecord(raw,game);return;}catch(error){game.notify('복귀 기록을 사용할 수 없어요',error.message,true);}}
 // A first checkpoint preserves all accepted legacy progress; only its recovery health is made safe.
 const s=parseSave(serialize(game.save)),point=game.compositions.regions[s.region].safePoint.position,p=s.collection.find(p=>p.uid===s.party[0]);s.position=[point.x,point.z];p.hp=Math.max(p.hp,Math.ceil(maxHP(game.byId.get(p.id),p.level)*.5));p.status=null;s.survival.hunger=Math.max(35,s.survival.hunger);s.survival.thirst=Math.max(35,s.survival.thirst);const r=makeRecord(game,s,'initial');game.checkpoint={...r,save:s};try{game.resumeWritesBlocked=true;archiveOriginal(game);if(raw&&!storage.getItem(key+':invalid-original'))storage.setItem(key+':invalid-original',raw);storage.setItem(key,JSON.stringify(r));}catch(error){game.notify('최초 복귀 기록은 이번 실행 동안 유지돼요','브라우저 저장 실패: '+error.message,true);}}
export function checkpointBlock(game){const p=game.player;if(game.restoring||game.survivalDying)return '사망 복귀를 처리하고 있어요';if(game.phase!=='playing'||game.transitioning)return '지역을 불러오고 있어요';if(game.capture)return '포획이 끝난 뒤 저장하세요';if(game.partnerChanging||game.nestBusy||game.fieldAction||game.tasks.length||game.projectiles.length)return '진행 중인 동작이 끝난 뒤 저장하세요';if(!p||p.hp<=0||p.actionTime>0)return '동작을 마친 뒤 저장하세요';if(game.wild.some(a=>a.hp>0&&(a.boss||a.angry)&&a.model.position.distanceTo(p.model.position)<26))return '전투에서 벗어난 뒤 저장하세요';if(p.hp<p.maxHp*.25||p.status)return '먼저 쉼터에서 체력과 상태를 회복하세요';if(game.save.survival.hunger<25||game.save.survival.thirst<25)return '허기·갈증 수치를 각각 25 이상 보충하세요';return '';}
export function saveAtStation(game,station){const reason=checkpointBlock(game);if(reason||game.checkpointWriting){game.notify('탐험 기록을 저장하지 못했어요',reason);return false;}if(!station||station.kind!=='save'||!game.world.interactions.includes(station)||Math.hypot(station.x-game.player.model.position.x,station.z-game.player.model.position.z)>4.5)return false;game.checkpointWriting=true;try{archiveSupplyOriginal(game);game.syncPlayer();const s=parseSave(serialize(game.save));s.position=[game.player.model.position.x,game.player.model.position.z];const r=makeRecord(game,s),raw=JSON.stringify(r),storage=game.storage||globalThis.localStorage;storage.setItem(checkpointKey(game.save),raw);game.checkpoint={...r,save:s};game.notify('▣ 탐험 기록 저장 완료',r.place+' · '+new Date(r.savedAt).toLocaleTimeString('ko-KR'));game.persist();game.emit('refreshPanel');return true;}catch(error){game.notify('저장 실패 — 이전 복귀 기록을 유지해요',error.message,true);return false;}finally{game.checkpointWriting=false;}}
export function checkpointSummary(game){const r=game.checkpoint;return r?`▣ ${r.place} · ${new Date(r.savedAt).toLocaleString('ko-KR')}${r.kind==='initial'?' · 최초 안전 기록':''}`:'복귀 기록 없음';}
export async function restoreCheckpoint(game){if(game.restoring||game.survivalDying)return false;game.survivalDying=true;game.restoring=true;game.phase='recovering';game.keys.clear();game.cancelCameraDrag?.();game.closePanel();game.regionEpoch++;game.clearActors();game.world.clearEffects?.();game.tasks=[];game.projectiles=[];game.moveChoice=null;game.deferredMovePrompts=new Set();game.pendingCompletion=false;game.moveManagerUid=null;game.campSelection=null;game.selectedInteraction=null;game.runeSequence=[];game.autosave=0;game.spawnIndex=0;game.needsWarned=false;game.expedition.selectedLandmark=null;game.notify('생존 수치가 고갈되어 쓰러졌어요','마지막 저장대 기록으로 돌아갑니다. 이후의 포획·아이템·경험치·보상·진행은 되돌아가요.',true);
 try{const record=validateRecord(JSON.stringify(game.checkpoint),game),settings={...game.save.settings};game.save=record.save;game.save.settings=settings;game.expedition.timer=0;game.expedition.previousWeather=game.save.weather;await game.enterRegion(game.save.region,game.save.position);game.player.invincible=3;game.lastFrame=performance.now();game.restoring=false;game.survivalDying=false;game.persist();game.notify('저장한 탐험 기록으로 복귀했어요',checkpointSummary(game)+' · 저장 이후 진행은 되돌렸어요.',true);return true;}catch(error){game.phase='recovery-error';game.restoring=false;game.notify('복귀를 완료하지 못했어요','기록을 섞거나 자동 저장하지 않았어요. '+error.message,true);game.emit('recoveryError',error.message);return false;}}
