// Species-specific locomotion; water type alone does not imply an aquatic body.
export const SWIMMERS=new Set([72,73,90,91,116,117,118,119,120,121,129,130,131]);
export const AMPHIBIANS=new Set([7,8,9,54,55,60,61,62,79,80,86,87,98,99,138,139,140,141]);
const inside=(x,z,poly=[])=>{let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
export const bodyAt=(world,x,z)=>(world.composition?.waterBodies||[]).find(b=>inside(x,z,b.polygon)&&!(b.holes||[]).some(h=>inside(x,z,h.polygon||h)));
function pathDistance(x,z,path){let d=Infinity;for(let i=1;i<path.points.length;i++){const a=path.points[i-1],b=path.points[i],dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz)));d=Math.min(d,Math.hypot(x-a[0]-dx*t,z-a[1]-dz*t));}return d;}
export function habitatValid(game,spec,x,z,from=null,{spacing=false}={}){const w=game.world,c=w.composition;if(!c)return true;const b=c.playableBounds;if(x<b.min[0]+.8||x>b.max[0]-.8||z<b.min[1]+.8||z>b.max[1]-.8)return false;const [cx,cz]=w.collision(x,z,.6);if(Math.hypot(cx-x,cz-z)>.05)return false;const water=bodyAt(w,x,z),swim=SWIMMERS.has(spec.id||spec.speciesId);if(water?.kind==='lava'||(swim?water?.kind!=='water':water?.kind==='water'&&!AMPHIBIANS.has(spec.id||spec.speciesId)))return false;const safe=c.safePoint;if(Math.hypot(x-safe.position.x,z-safe.position.z)<Math.max(6.5,safe.radius+2))return false;if(c.paths.some(p=>pathDistance(x,z,p)<Math.min(1.5,p.width*.32)))return false;
 const pocket=spec.pocket;if(pocket&&Math.hypot((x-pocket.center[0])/pocket.radius[0],(z-pocket.center[1])/pocket.radius[1])>1)return false;const y=water&&(swim||AMPHIBIANS.has(spec.id||spec.speciesId))?water.surfaceY:w.height(x,z);if(!Number.isFinite(y))return false;if(from){const start=bodyAt(w,from.x,from.z),py=swim&&start?start.surfaceY:w.height(from.x,from.z),distance=Math.hypot(x-from.x,z-from.z);if(Math.abs(y-py)>Math.max(.35,distance*.75))return false;for(let i=1;i<Math.ceil(distance/.3);i++){const t=i/Math.ceil(distance/.3);if(!habitatValid(game,spec,from.x+(x-from.x)*t,from.z+(z-from.z)*t,null))return false;}}
 if(spacing&&game.wild.some(a=>a.hp>0&&a!==spec&&Math.hypot(a.model.position.x-x,a.model.position.z-z)<2.2))return false;return true;}
export function ecologyPosition(game,entry,index=0,origin=null){const c=game.world.composition||game.compositions?.regions[game.save.region];if(!c)return origin||{x:10,z:14};const id=entry.speciesId,method=entry.method||'field',pockets=c.ecologyPockets.filter(p=>p.speciesIds.includes(id)&&p.method===method),candidates=[];
 for(let n=0;n<pockets.length;n++){const pocket=pockets[(n+index)%pockets.length];for(let j=0;j<96;j++){const angle=(j+index*7+id*3)*2.3999632297,r=Math.sqrt(((j*37+index*13)%97+.5)/97)*.94,x=pocket.center[0]+Math.cos(angle)*pocket.radius[0]*r,z=pocket.center[1]+Math.sin(angle)*pocket.radius[1]*r;const spec={id,pocket};if(habitatValid(game,spec,x,z,null,{spacing:true}))candidates.push({x,z,pocket,score:origin?Math.hypot(x-origin.x,z-origin.z):j+n*.01});}}
 if(!pockets.length&&origin){for(let j=0;j<480;j++){const a=j*2.3999632297,r=Math.sqrt(j)*.65,x=origin.x+Math.cos(a)*r,z=origin.z+Math.sin(a)*r;if(habitatValid(game,{id},x,z,null,{spacing:true}))candidates.push({x,z,score:r});}}
 candidates.sort((a,b)=>a.score-b.score);return candidates[0]||null;}
export function constrainWild(game,actor,previous){const pos=actor.model.position;if(!habitatValid(game,actor,pos.x,pos.z,previous)){pos.x=previous.x;pos.y=previous.y;pos.z=previous.z;actor.angle=Math.atan2(actor.home.x-pos.x,actor.home.z-pos.z);actor.angry=actor.boss||false;actor.moving=false;actor.dash=null;actor.recoil=null;}}
