import * as supplies from './supplies.mjs';
import {caughtCount} from './core.mjs';
import {t,entity,currentLocale} from './i18n.mjs';
import {worldText,MILESTONES} from './expedition.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Place labels in real buttons, not on top of the map geometry.
export function atlasPoints(g){const e=g.expedition,c=e.region,state=e.state,points=[],add=(id,kind,name,x,z,detail='')=>points.push({id,kind,name,x,z,detail});
 for(const i of g.world.interactions||[]){if(i.kind==='food')add('food:'+i.dropId,'food','떨어진 열매',i.x,i.z,'가까이에서 먹으면 허기를 회복해요.');else if(i.kind==='special'&&i.acquisition?.kind==='boss'&&state.landmarks.includes(c.specialBindings.find(b=>b.speciesId===i.acquisition.speciesId)?.landmarkId))add('boss:'+i.acquisition.speciesId,'boss',g.byId.get(i.acquisition.speciesId).name,i.x,i.z,'성역의 주인을 만나 포획에 도전하세요.');else if(i.kind==='save')add('save:'+i.safeId,'save','탐험 기록 저장대',i.x,i.z,'E / 행동 버튼으로 사망 복귀 기록을 확정해요.');else if(i.kind==='drink'&&g.save.survival.provisions.sources[i.sourceId]?.discovered){const source=supplies.WATER_SOURCES.find(s=>s.id===i.sourceId);add('water:'+i.sourceId,'water',source.name,i.x,i.z,supplies.sourceReady(g.save,source)?'직접 마시기와 물통 채우기를 따로 선택할 수 있어요.':source.condition);}else if(['camp','rations','shop','research'].includes(i.kind))add(i.kind,i.kind,{camp:'친구 교체',rations:'캠프 기본 식량',shop:'보급 수레',research:'연구대'}[i.kind],i.x,i.z,{camp:'파트너와 캠프 친구를 비교하고 교체해요.',rations:supplies.rationReason(g.save)||'기본 식량을 보충할 수 있어요.',shop:'연구 자금으로 몬스터볼과 도구를 구매해요.',research:'화석 복원과 특별한 포켓몬 만남을 확인하세요.'}[i.kind]);else if(i.kind==='capability'&&!points.some(p=>p.id==='skill:'+i.shortcut.id)){const info=e.capabilityInfo?.(i.shortcut.capability);add('skill:'+i.shortcut.id,'skill',i.name,i.x,i.z,info?(info.learned?info.description:info.requirement)+' '+info.usage:'');}}
 const safe=c.safePoint;if(state.safePoints.includes(safe.id))add('camp-rest','heal','캠프 쉼터',safe.position.x,safe.position.z,'함께하는 친구들의 체력을 회복해요.');
 for(const l of c.landmarks||[])if(state.landmarks.includes(l.id))add('landmark:'+l.id,'landmark',worldText(l.name),l.position.x,l.position.z,worldText(l.description));
 for(const exit of c.entrances||[]){const known=state.exits.includes(g.save.region+':'+exit.to)||g.save.discovered.includes(exit.to);add('exit:'+exit.to,'exit',known?g.biomeById.get(exit.to)?.name:'다른 지역으로 가는 길',exit.position.x,exit.position.z,g.canTravel(exit.to)?'이 길 끝에서 다음 지역으로 이동해요.':e.requirementText(exit.to));}
 const goal=e.objective();if(goal.point)add('goal','goal',goal.name,goal.point.x,goal.point.z,goal.description);
 return points;
}
const atlasIcon=kind=>({save:'▣',water:'💧',heal:'+',camp:'♧',rations:'●',shop:'◒',research:'◇',skill:'✦',landmark:'○',exit:'↗',goal:'◆',food:'●',boss:'!'}[kind]||'○');
export function layoutMapMarkers(points,w,h,reserved=[]){const groups=[];
 for(const point of points){let group=groups.find(g=>Math.hypot(g.anchorX-point.x,g.anchorY-point.y)<28);if(group){group.members.push(point);group.anchorX=group.members.reduce((n,p)=>n+p.x,0)/group.members.length;group.anchorY=group.members.reduce((n,p)=>n+p.y,0)/group.members.length;}else groups.push({anchorX:point.x,anchorY:point.y,members:[point]});}
 const placed=reserved.map(p=>({...p}));for(const group of groups){let spot;for(let radius=0;radius<=Math.max(w,h)&&!spot;radius+=18){const steps=radius?16:1;for(let n=0;n<steps;n++){const x=Math.max(18,Math.min(w-18,group.anchorX+Math.cos(n*Math.PI*2/steps)*radius)),y=Math.max(26,Math.min(h-28,group.anchorY+Math.sin(n*Math.PI*2/steps)*radius));if(placed.every(p=>Math.hypot(p.x-x,p.y-y)>=30)){spot={x,y};break;}}}if(!spot){const nearest=groups.filter(g=>g.x!==undefined).sort((a,b)=>Math.hypot(a.x-group.anchorX,a.y-group.anchorY)-Math.hypot(b.x-group.anchorX,b.y-group.anchorY))[0];if(nearest){nearest.members.push(...group.members);group.merged=true;continue;}spot={x:w/2,y:h/2};}Object.assign(group,spot);placed.push(spot);}
 return groups.filter(g=>!g.merged);
}
function atlasSelection(ui){const g=ui.game,all=atlasPoints(g),subset=g.atlasCluster?all.filter(p=>g.atlasCluster.includes(p.id)):all,selected=all.find(p=>p.id===g.atlasSelected);const node=document.querySelector('#atlas-selection');if(!node)return;
 node.innerHTML=`<div class="atlas-selection-heading"><b>${g.atlasCluster?'선택한 표식 주변':'지도에 표시된 장소'}</b>${g.atlasCluster?'<button id="atlas-all">전체 장소</button>':''}</div><div class="atlas-point-list">${subset.map(p=>`<button data-map-point="${esc(p.id)}" aria-pressed="${p.id===selected?.id}"><span aria-hidden="true">${atlasIcon(p.kind)}</span><b>${esc(p.name)}</b></button>`).join('')}</div>${selected?`<div class="atlas-place-detail"><strong>${atlasIcon(selected.kind)} ${esc(selected.name)} <small>약 ${Math.round(Math.hypot(selected.x-g.player.model.position.x,selected.z-g.player.model.position.z))}m</small></strong><p>${esc(selected.detail)}</p><button id="atlas-walk">이곳까지 걸어가기</button></div>`:''}`;
 document.querySelectorAll('[data-map-point]').forEach(b=>b.onclick=()=>{g.atlasSelected=b.dataset.mapPoint;atlasSelection(ui);drawMap(document.querySelector('#atlas-canvas'),g,true);});document.querySelector('#atlas-all')?.addEventListener('click',()=>{g.atlasCluster=null;atlasSelection(ui);});document.querySelector('#atlas-walk')?.addEventListener('click',()=>{g.closePanel();g.walkTo(selected);});
}
export function renderAtlas(ui){const g=ui.game,e=g.expedition;if(!e)return;const state=e.state,c=e.region,goal=e.objective();g.atlasCluster=null;
 document.querySelector('#panel-body').innerHTML=`<div class="atlas-readable"><section class="atlas-local"><div class="atlas-toolbar"><b>${esc(g.biomeById.get(g.save.region).name)}</b><div><button id="atlas-less" aria-label="지도 축소">−</button><button id="atlas-fit">전체</button><button id="atlas-more" aria-label="지도 확대">+</button></div></div><canvas id="atlas-canvas" width="720" height="440" aria-label="현재 지역 지도. 표식을 누르거나 아래 장소 목록을 선택하세요."></canvas><p class="atlas-help">▲ 내 위치 · ◆ 다음 목표 · 숫자는 가까운 장소의 묶음이에요. 표식을 눌러 장소를 고르세요.</p><div id="atlas-selection"></div></section><section class="atlas-goal-summary"><span class="eyebrow">${t('exp.next')}</span><h2>${esc(goal.name)}</h2><p>${esc(goal.description)}</p>${state.habitatTarget?`<button id="clear-habitat">${t('exp.clearTrack')}</button>`:''}</section><details class="atlas-guide"><summary>필드 능력 · 해금 조건과 사용법</summary><p class="notice">특정 포켓몬 계열을 잡거나 도감 조건을 채우면 자동 해금돼요. 기술머신 소비나 전투 기술 장착은 필요 없어요.</p><div class="field-guide-grid">${e.compositions.fieldCapabilities.map(cap=>{const info=e.capabilityInfo(cap.id);return `<article class="field-guide ${info.learned?'learned':''}"><h3>${info.learned?'✓':'◇'} ${esc(info.name)} <small>${info.learned?'사용 가능':'미해금'}</small></h3><p>${esc(info.description)}</p><p>${esc(info.requirement)}</p><small>${esc(info.usage)}</small></article>`;}).join('')}</div></details><details class="atlas-guide"><summary>발견한 수원 · ${supplies.sourceList(g).length}곳</summary><div class="supply-map-list">${supplies.sourceList(g).map(s=>`<p>💧 ${esc(s.name)} · ${esc(g.biomeById.get(s.region).name)}<small>${supplies.sourceReady(g.save,s)?'직접 마시기 · 물통 채우기':esc(s.condition)}</small>${s.region===g.save.region?`<button data-walk-source="${s.id}">수원까지 걸어가기</button>`:''}</p>`).join('')}<p>화산·연구단지에는 기본 수원이 없어요. 물통을 준비하세요.</p></div></details><details class="atlas-guide"><summary>지역 이동 · 5개 탐험지</summary><div class="atlas-regions">${g.biomes.map((b,i)=>{const visited=g.save.discovered.includes(b.id),open=g.canTravel(b.id);return `<article class="atlas-region ${b.id===g.save.region?'current':''} ${open?'':'locked'}"><small>${String(i+1).padStart(2,'0')} · ${b.id===g.save.region?t('exp.current'):visited?t('exp.discovered'):open?t('exp.open'):t('exp.unseen')}</small><h3>${esc(b.name)}</h3><p>${esc(open?b.description:e.requirementText(b.id))}</p><button data-travel="${b.id}">${open?visited?t('exp.safe'):t('exp.visit'):t('exp.permit',{count:b.requirements.caughtCount||0,now:caughtCount(g.save)})}</button></article>`;}).join('')}</div></details></div>`;
 for(const [id,delta] of [['atlas-less',-.5],['atlas-more',.5]])document.querySelector('#'+id).onclick=()=>{g.atlasZoom=Math.max(1,Math.min(3,(g.atlasZoom||1)+delta));drawMap(document.querySelector('#atlas-canvas'),g,true);};document.querySelector('#atlas-fit').onclick=()=>{g.atlasZoom=1;drawMap(document.querySelector('#atlas-canvas'),g,true);};
 document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>g.travel(b.dataset.travel));document.querySelectorAll('[data-walk-source]').forEach(b=>b.onclick=()=>{const source=supplies.WATER_SOURCES.find(s=>s.id===b.dataset.walkSource);g.closePanel();g.walkTo(source);});document.querySelector('#clear-habitat')?.addEventListener('click',()=>{e.state.habitatTarget=null;renderAtlas(ui);});
 const canvas=document.querySelector('#atlas-canvas');canvas.onclick=event=>{const r=canvas.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top,group=(canvas.mapGroups||[]).find(m=>Math.hypot(m.x-x,m.y-y)<23);if(group){g.atlasCluster=group.members.map(p=>p.id);g.atlasSelected=group.members[0].id;atlasSelection(ui);drawMap(canvas,g,true);document.querySelector('#atlas-selection')?.scrollIntoView({block:'nearest',behavior:'smooth'});}};atlasSelection(ui);drawMap(canvas,g,true);
}
export function mapViewport(g,w,h,large=false){
 const bounds=g.expedition.region.playableBounds||{min:[-68,-68],max:[68,68]},[minX,minZ]=bounds.min,[maxX,maxZ]=bounds.max;
 const zoom=large?Math.max(1,Math.min(3,g.atlasZoom||1)):Math.max(1,Math.min(3,g.minimapZoom??1.35));
 const scale=large?Math.min((w-36)/(maxX-minX),(h-42)/(maxZ-minZ))*zoom:(Math.min(w,h)-20)/(Math.max(maxX-minX,maxZ-minZ)/zoom);
 const margin=14/scale,axis=(value,min,max,span)=>span>=max-min+margin*2?(min+max)/2:Math.max(min-margin+span/2,Math.min(max+margin-span/2,value));
 const center=large&&zoom===1?[(minX+maxX)/2,(minZ+maxZ)/2]:[axis(g.player.model.position.x,minX,maxX,w/scale),axis(g.player.model.position.z,minZ,maxZ,h/scale)];
 return {bounds,zoom,scale,center,project:q=>[w/2+(q[0]-center[0])*scale,h/2+(q[1]-center[1])*scale]};
}
export function drawMap(canvas,g,large=false){
 if(!canvas||!g.expedition||!g.player)return;
 const w=canvas.clientWidth||Number(canvas.dataset.logicalWidth)||canvas.width,h=canvas.clientHeight||Number(canvas.dataset.logicalHeight)||canvas.height,dpr=Math.min(2,globalThis.devicePixelRatio||1);
 if(!w||!h)return;
 const bw=Math.round(w*dpr),bh=Math.round(h*dpr);if(canvas.width!==bw)canvas.width=bw;if(canvas.height!==bh)canvas.height=bh;
 canvas.dataset.logicalWidth=w;canvas.dataset.logicalHeight=h;
 const ctx=canvas.getContext('2d'),e=g.expedition,c=e.region,s=e.state,p=g.player.model.position,view=mapViewport(g,w,h,large),{project,scale}=view;
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#10272e';ctx.fillRect(0,0,w,h);
 const [bx,by]=project(view.bounds.min);ctx.fillStyle='#365748';ctx.fillRect(bx,by,(view.bounds.max[0]-view.bounds.min[0])*scale,(view.bounds.max[1]-view.bounds.min[1])*scale);
 const polygon=points=>{points.forEach((q,i)=>{const [x,y]=project(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();};
 const block=(q,width,length,rotation,fill,stroke=null)=>{const [x,y]=project(q);ctx.save();ctx.translate(x,y);ctx.rotate(-rotation);ctx.fillStyle=fill;ctx.fillRect(-width*scale/2,-length*scale/2,width*scale,length*scale);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.strokeRect(-width*scale/2,-length*scale/2,width*scale,length*scale);}ctx.restore();};
 for(const shelf of c.terrain?.shelves||[]){ctx.fillStyle=shelf.height<0?'#1e353b':'#566966';ctx.beginPath();polygon(shelf.polygon);ctx.fill();}
 for(const structure of c.structures||[])if(structure.kind==='floor')block([structure.position[0],structure.position[2]],structure.size[0],structure.size[2],structure.rotation||0,'#50696e');
 for(const water of c.waterBodies||[]){ctx.fillStyle=water.kind==='lava'?'#bc5939':water.kind==='ice'?'#a4d3dc':'#277c9c';ctx.strokeStyle=water.kind==='lava'?'#ffb375':water.kind==='ice'?'#d8f7f4':'#65b7ce';ctx.lineWidth=1.4;ctx.beginPath();for(const points of [water.polygon,...water.holes||[]])polygon(points);ctx.fill('evenodd');ctx.stroke();}
 ctx.lineCap='round';ctx.lineJoin='round';
 for(const path of c.paths||[]){ctx.beginPath();path.points.forEach((q,i)=>{const [x,y]=project(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});const width=Math.max(2.6,path.width*scale*.72);ctx.strokeStyle='#193b3c';ctx.lineWidth=width+2.4;ctx.stroke();ctx.strokeStyle='#ddcf9d';ctx.lineWidth=width;ctx.stroke();}
 for(const prop of c.props||[])if(prop.walkSurface?.kind==='bridge-deck'){const deck=prop.walkSurface;block([prop.x,prop.z],deck.width,deck.length,deck.rotation??prop.rotation??0,'#e4c283','#423b30');}
 for(const structure of c.structures||[])if(['wall','cliff','door'].includes(structure.kind)){
  if(structure.kind==='door'&&g.world.gates?.find(gate=>gate.spec.id===structure.id)?.collider.disabled)continue;
  block([structure.position[0],structure.position[2]],Math.max(.6,structure.size[0]),Math.max(.6,structure.size[2]),structure.rotation||0,structure.kind==='door'?'#f28e75':'#83918a','#193139');
 }
 const marker=(q,color,kind,name='',edge=false,screen=null)=>{
  let [x,y]=screen||project(q);const outside=x<13||x>w-13||y<13||y>h-13;if(outside&&!edge)return;
  if(outside){const dx=x-w/2,dy=y-h/2,factor=Math.min((w/2-14)/Math.max(.001,Math.abs(dx)),(h/2-14)/Math.max(.001,Math.abs(dy)));x=w/2+dx*factor;y=h/2+dy*factor;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));ctx.fillStyle='#152d34';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.strokeStyle='#12272d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(-5,-6);ctx.lineTo(-2,0);ctx.lineTo(-5,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();return;}
  const r=kind==='landmark'?3:kind==='goal'?8:7;
  ctx.save();ctx.translate(x,y);ctx.fillStyle='#10272f';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();
  if(kind==='goal'){ctx.moveTo(0,-r-2);ctx.lineTo(r+2,0);ctx.lineTo(0,r+2);ctx.lineTo(-r-2,0);ctx.closePath();}else ctx.arc(0,0,r+2,0,Math.PI*2);
  ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.strokeStyle=color;ctx.lineWidth=2.2;
  if(kind==='heal'){ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(4,0);ctx.moveTo(0,-4);ctx.lineTo(0,4);ctx.stroke();}
  else if(kind==='save'){ctx.strokeRect(-4,-5,8,10);ctx.beginPath();ctx.moveTo(-2,-2);ctx.lineTo(2,-2);ctx.moveTo(-2,1);ctx.lineTo(2,1);ctx.stroke();}else if(kind==='water'){ctx.beginPath();ctx.moveTo(0,-6);ctx.bezierCurveTo(-2,-2,-5,0,-4,3);ctx.bezierCurveTo(-2,7,4,6,4,2);ctx.bezierCurveTo(4,0,1,-4,0,-6);ctx.fill();}
  else if(kind==='exit'){ctx.beginPath();ctx.moveTo(-4,4);ctx.lineTo(4,-4);ctx.moveTo(-1,-4);ctx.lineTo(4,-4);ctx.lineTo(4,1);ctx.stroke();}
  else if(kind==='goal'){ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(4,0);ctx.lineTo(0,4);ctx.lineTo(-4,0);ctx.closePath();ctx.fill();}
  else if(kind==='boss'){ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText('!',0,5);}
  else if(kind!=='cluster'){ctx.beginPath();ctx.arc(0,0,kind==='food'?4:2,0,Math.PI*2);ctx.fill();}
  ctx.restore();
  if(large&&kind==='cluster'){ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(name,x,y+4);}
 };
 ctx.fillStyle='#10272f';ctx.fillRect(5,4,19,19);ctx.fillStyle='#f0f3da';ctx.textAlign='center';ctx.font='bold 12px sans-serif';ctx.fillText('N',14,18);
 const units=large?20:10;ctx.strokeStyle='#eff4da';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(10,h-11);ctx.lineTo(10+units*scale,h-11);ctx.stroke();ctx.textAlign='left';ctx.font='10px sans-serif';ctx.strokeStyle='#10272f';ctx.lineWidth=3;ctx.strokeText(units+' m',10,h-17);ctx.fillStyle='#eff4da';ctx.fillText(units+' m',10,h-17);
 const goal=e.objective();
 if(large){const points=atlasPoints(g).map(point=>{const [x,y]=project([point.x,point.z]);return {...point,worldX:point.x,worldZ:point.z,x,y};}).filter(point=>point.x>=0&&point.x<=w&&point.y>=0&&point.y<=h),[playerX,playerY]=project([p.x,p.z]),groups=layoutMapMarkers(points,w,h,[{x:playerX,y:playerY}]);canvas.mapGroups=groups;canvas.dataset.mapGroups=JSON.stringify(groups.map(m=>({x:m.x,y:m.y,ids:m.members.map(p=>p.id)})));
  for(const group of groups){const selected=group.members.some(p=>p.id===g.atlasSelected),first=group.members.find(p=>p.kind==='goal')||group.members[0],color=selected?'#ffffff':first.kind==='goal'?'#ffe17c':first.kind==='water'?'#78dfff':first.kind==='save'?'#ffe3a1':'#c3edda';if(Math.hypot(group.x-group.anchorX,group.y-group.anchorY)>2){ctx.strokeStyle='#adc7b9';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(group.anchorX,group.anchorY);ctx.lineTo(group.x,group.y);ctx.stroke();}marker([first.worldX,first.worldZ],color,group.members.length>1?'cluster':first.kind,group.members.length>1?String(group.members.length):'',false,[group.x,group.y]);if(selected){ctx.strokeStyle='#ffffff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(group.x,group.y,14,0,Math.PI*2);ctx.stroke();}}
 }else{
 for(const l of c.landmarks||[])if(s.landmarks.includes(l.id))marker([l.position.x,l.position.z],'#bcd2c2','landmark',worldText(l.name));
 const safe=c.safePoint;if(s.safePoints.includes(safe.id))marker([safe.position.x,safe.position.z],'#9cf2ae','heal',large?worldText(safe.name):'');
 for(const i of g.world.interactions||[])if(i.kind==='save')marker([i.x,i.z],'#ffe3a1','save',large?'탐험 기록 저장대':'');else if(i.kind==='drink'&&g.save.survival.provisions.sources[i.sourceId]?.discovered)marker([i.x,i.z],g.save.survival.provisions.sources[i.sourceId]?.unlocked?'#78dfff':'#bfa277','water',large?(supplies.WATER_SOURCES.find(s=>s.id===i.sourceId)?.name+' '+(g.save.survival.provisions.sources[i.sourceId]?.unlocked?'':'(해금 필요)')):'');else if(i.kind==='food')marker([i.x,i.z],'#ffbc7a','food',large?t('survival.mapFood'):'');
 for(const exit of c.entrances||[]){const known=s.exits.includes(g.save.region+':'+exit.to)||g.save.discovered.includes(exit.to);marker([exit.position.x,exit.position.z],g.canTravel(exit.to)?'#b2ebcb':'#f3a58f','exit',large&&known?g.biomeById.get(exit.to)?.name:'');}
 for(const i of g.world.interactions||[])if(i.kind==='special'&&i.acquisition.kind==='boss'&&s.landmarks.includes(c.specialBindings.find(b=>b.speciesId===i.acquisition.speciesId)?.landmarkId))marker([i.x,i.z],'#efa4ef','boss');
 if(goal.point)marker([goal.point.x,goal.point.z],'#ffe17c','goal',large?goal.name:'',!large);
 }
 const [px,py]=project([p.x,p.z]);ctx.save();ctx.translate(px,py);ctx.fillStyle='#133842';ctx.strokeStyle='#6fefff';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.rotate(-g.player.model.rotation.y);ctx.fillStyle='#ffffff';ctx.strokeStyle='#164a53';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(0,8);ctx.lineTo(-6,-6);ctx.lineTo(0,-3);ctx.lineTo(6,-6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
 canvas.dataset.player=p.x.toFixed(1)+','+p.z.toFixed(1);canvas.dataset.playerScreen=px.toFixed(1)+','+py.toFixed(1);canvas.dataset.mapScale=String(scale);canvas.dataset.zoom=String(view.zoom);canvas.dataset.goal=goal.name;canvas.dataset.discoveredLandmarks=String(s.landmarks.length);canvas.dataset.drinkSpots=String((g.world.interactions||[]).filter(i=>i.kind==='drink'&&g.save.survival.provisions.sources[i.sourceId]?.discovered).length);canvas.dataset.foodDrops=String((g.world.interactions||[]).filter(i=>i.kind==='food').length);
}
export function updateNavigation(ui){const g=ui.game,e=g.expedition;if(!e||!g.player)return;let mini=document.querySelector('#minimap');
 if(!mini){document.querySelector('#hud').insertAdjacentHTML('beforeend','<div class="minimap-wrap"><div class="minimap-heading"><button id="minimap-toggle" aria-expanded="false" aria-controls="minimap"><strong id="minimap-title"></strong><span aria-hidden="true"> +</span></button><div class="minimap-controls"><button id="minimap-less">−</button><button id="minimap-more">+</button></div></div><canvas id="minimap" width="220" height="220"></canvas><div class="minimap-legend"><span><i class="mini-you"></i><b data-mini-label="player"></b></span><span><i class="mini-goal"></i><b data-mini-label="goal"></b></span><span><i class="mini-heal">+</i><b data-mini-label="heal"></b></span><span><i class="mini-water"></i><b data-mini-label="water"></b></span></div><div class="minimap-save-key">▣ 저장대</div><div class="minimap-footer"><button id="minimap-open"></button></div></div><button id="compass" class="compass" aria-label="다음 목표 자세히 보기"></button><div id="tutorial-hint" class="tutorial-hint"></div>');mini=document.querySelector('#minimap');document.querySelector('#minimap-toggle').onclick=()=>{if(g.target){g.openPanel('map');return;}ui.minimapExpanded=!ui.minimapExpanded;ui.updateTimer=0;};document.querySelector('#compass').onclick=()=>g.openPanel('map');document.querySelector('.minimap-footer').prepend(document.querySelector('#region-name'));document.querySelector('#minimap-open').onclick=()=>g.openPanel('map');for(const [id,delta] of [['minimap-less',-.35],['minimap-more',.35]])document.querySelector('#'+id).onclick=()=>{g.minimapZoom=Math.max(1,Math.min(3,Math.round(((g.minimapZoom??1.35)+delta)*100)/100));drawMap(mini,g);};}
 const mapButton=document.querySelector('#minimap-open');mapButton.textContent='M ↗';mapButton.title='M · '+t('minimap.full');mapButton.setAttribute('aria-label',t('minimap.full'));document.querySelector('#region-name').title=g.biomeById.get(g.save.region).name;document.querySelector('#minimap-title').textContent=t('minimap.nearby');document.querySelector('#minimap-title').title=g.biomeById.get(g.save.region).name;mini.setAttribute('aria-label',t('minimap.aria',{region:g.biomeById.get(g.save.region).name}));for(const key of ['player','goal','heal','water'])document.querySelector('[data-mini-label="'+key+'"]').textContent=t('minimap.'+key);
 for(const [id,key,disabled] of [['minimap-less','out',(g.minimapZoom??1.35)<=1],['minimap-more','in',(g.minimapZoom??1.35)>=3]]){const button=document.querySelector('#'+id);button.setAttribute('aria-label',t('minimap.zoom'+key));button.title=t('minimap.zoom'+key);button.disabled=disabled;}
 const expanded=!!ui.minimapExpanded&&!g.target;mini.closest('.minimap-wrap').classList.toggle('is-collapsed',!expanded);document.querySelector('#minimap-toggle').setAttribute('aria-expanded',String(expanded));document.querySelector('#minimap-toggle span').textContent=expanded?' −':' +';if(expanded)drawMap(mini,g);if(g.panel==='map')drawMap(document.querySelector('#atlas-canvas'),g,true);const goal=e.objective(),count=caughtCount(g.save),next=MILESTONES.find(n=>n>count)||151,local=[...new Set(g.biomeById.get(g.save.region).spawnTable.map(s=>s.speciesId))],unknown=local.filter(id=>!g.save.dex[id]?.caught).length;const stamp=[goal.name,goal.description,count,unknown,currentLocale()].join('|');const goalChanged=ui.objectiveStamp!==stamp;if(goalChanged){ui.objectiveStamp=stamp;document.querySelector('#objective').innerHTML=`<span class="eyebrow">${t('exp.next')}</span><b>${esc(goal.name)}</b><p>${esc(goal.description)}</p><small>${t('exp.nextMilestone',{count,goal:next})}</small><small>${t('exp.localResearch',{percent:local.length?Math.round((local.length-unknown)/local.length*100):100,unknown})}</small>`;}
 const compass=document.querySelector('#compass');if(goal.point){const dx=goal.point.x-g.player.model.position.x,dz=goal.point.z-g.player.model.position.z,angle=Math.atan2(dx,dz)-g.world.orbit.yaw;compass.innerHTML=`<span style="display:inline-block;transform:rotate(${-angle*180/Math.PI}deg)">↑</span> ${esc(t('exp.distance',{name:goal.name,distance:Math.round(Math.hypot(dx,dz))}))}`;}else compass.textContent=goal.name;
 const objective=document.querySelector('#objective');if(goalChanged&&goal.point){objective.insertAdjacentHTML('beforeend',`<button id="walk-goal">${t('exp.walkGoal')} ↗</button>`);document.querySelector('#walk-goal').onclick=()=>g.walkTo(goal.point);}
 const tutorial=document.querySelector('#tutorial-hint');tutorial.textContent=globalThis.matchMedia?.('(pointer:coarse)').matches?'왼쪽을 끌어 이동 · 오른쪽을 쓸어 시점 · 기술 +로 전투 기술 열기':e.tutorial();tutorial.classList.toggle('hidden',!tutorial.textContent||!!g.panel);mini.closest('.minimap-wrap').classList.toggle('hidden',!!g.panel);
}
