import * as supplies from './supplies.mjs';
import {caughtCount} from './core.mjs';
import {t,entity,currentLocale} from './i18n.mjs';
import {worldText,MILESTONES} from './expedition.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderAtlas(ui){const g=ui.game,e=g.expedition;if(!e)return;const state=e.state,c=e.region,goal=e.objective();document.querySelector('#panel-body').innerHTML=`<div class="atlas-top"><div class="atlas-local"><div class="section-caption"><b>${t('exp.mapLocal')} · ${g.biomeById.get(g.save.region).name}</b><span>${t('exp.current')}</span></div><canvas id="atlas-canvas" width="720" height="440" aria-label="${t('exp.mapLocal')}"></canvas><small>${t('exp.mapLegend')}</small><p class="notice">${t('exp.fog')}</p><button id="walk-camp">캠프까지 걸어가기</button></div><aside class="atlas-objective"><span class="eyebrow">${t('exp.next')}</span><h2>${esc(goal.name)}</h2><p>${esc(goal.description)}</p><div class="landmark-list">${c.landmarks.map(l=>`<button data-landmark="${l.id}" ${state.landmarks.includes(l.id)||goal.name===worldText(l.name)?'':'disabled'}>${state.landmarks.includes(l.id)?'✓':'◇'} ${state.landmarks.includes(l.id)||goal.name===worldText(l.name)?esc(worldText(l.name)):t('exp.unseen')}</button>`).join('')}</div><p>${t('exp.landmarkProgress',{done:c.landmarks.filter(l=>state.landmarks.includes(l.id)).length,total:c.landmarks.length})}</p><p>${t('exp.researchTask',{done:Math.min(3,state.research[g.save.region]?.caught.length||0)})}</p>${state.habitatTarget?`<button id="clear-habitat">${t('exp.clearTrack')}</button>`:''}<h3>발견한 식수대</h3><div class="supply-map-list">${supplies.sourceList(g).map(s=>`<p>💧 ${esc(s.name)} · ${esc(g.biomeById.get(s.region).name)}<small>${supplies.sourceReady(g.save,s)?'직접 마시기 · 물통 채우기':esc(s.condition)}</small>${s.region===g.save.region?`<button data-walk-source="${s.id}">수원까지 걸어가기</button>`:''}</p>`).join('')}<small>화산·연구단지에는 기본 수원이 없어요. 물통을 준비하세요.</small></div><h3>${t('exp.capability')}</h3><div class="capability-list">${e.compositions.fieldCapabilities.map(cap=>`<span class="${e.has(cap.id)?'learned':''}" title="${esc(worldText(cap.description))}">${e.has(cap.id)?'✓':'◇'} ${worldText(cap.name)}</span>`).join('')}</div></aside></div><div class="atlas-regions">${g.biomes.map((b,i)=>{const visited=g.save.discovered.includes(b.id),open=g.canTravel(b.id),habitat=state.habitatTarget&&e.habitatRegions(state.habitatTarget).some(h=>h.id===b.id);return `<article class="atlas-region ${b.id===g.save.region?'current':''} ${open?'':'locked'} ${habitat?'habitat':''}"><small>${String(i+1).padStart(2,'0')} · ${b.id===g.save.region?t('exp.current'):visited?t('exp.discovered'):open?t('exp.open'):t('exp.unseen')}</small><h3>${esc(b.name)} ${habitat?'⌖':''}</h3><p>${open?b.description:esc(e.requirementText(b.id))}</p><small>Lv. ${b.levelRange.join('–')}</small><button data-travel="${b.id}">${open?visited?t('exp.safe'):t('exp.visit'):b.requirements.caughtCount?t('exp.permit',{count:b.requirements.caughtCount,now:caughtCount(g.save)}):t('exp.connected')}</button></article>`;}).join('')}</div>`;
 document.querySelector('#walk-camp').onclick=()=>{g.closePanel();g.walkTo(c.safePoint.position);};document.querySelectorAll('[data-walk-source]').forEach(b=>b.onclick=()=>{const source=supplies.WATER_SOURCES.find(s=>s.id===b.dataset.walkSource);g.closePanel();g.walkTo(source);});document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>g.travel(b.dataset.travel));document.querySelectorAll('[data-landmark]').forEach(b=>b.onclick=()=>{e.selectedLandmark=b.dataset.landmark;e.state.habitatTarget=null;g.closePanel();g.notify(t('exp.next'),worldText(c.landmarks.find(l=>l.id===b.dataset.landmark).name));});document.querySelector('#clear-habitat')?.addEventListener('click',()=>{e.state.habitatTarget=null;renderAtlas(ui);});drawMap(document.querySelector('#atlas-canvas'),g,true);
}
export function mapViewport(g,w,h,large=false){
 const bounds=g.expedition.region.playableBounds||{min:[-68,-68],max:[68,68]},[minX,minZ]=bounds.min,[maxX,maxZ]=bounds.max;
 const zoom=large?1:Math.max(1,Math.min(3,g.minimapZoom??1.35));
 const scale=large?Math.min((w-36)/(maxX-minX),(h-42)/(maxZ-minZ)):(Math.min(w,h)-20)/(Math.max(maxX-minX,maxZ-minZ)/zoom);
 const margin=14/scale,axis=(value,min,max,span)=>span>=max-min+margin*2?(min+max)/2:Math.max(min-margin+span/2,Math.min(max+margin-span/2,value));
 const center=large?[(minX+maxX)/2,(minZ+maxZ)/2]:[axis(g.player.model.position.x,minX,maxX,w/scale),axis(g.player.model.position.z,minZ,maxZ,h/scale)];
 return {bounds,zoom,scale,center,project:q=>[w/2+(q[0]-center[0])*scale,h/2+(q[1]-center[1])*scale]};
}
export function drawMap(canvas,g,large=false){
 if(!canvas||!g.expedition||!g.player)return;
 const w=canvas.clientWidth||Number(canvas.dataset.logicalWidth)||canvas.width,h=canvas.clientHeight||Number(canvas.dataset.logicalHeight)||canvas.height,dpr=Math.min(2,globalThis.devicePixelRatio||1);
 if(!w||!h)return;
 const bw=Math.round(w*dpr),bh=Math.round(h*dpr);if(canvas.width!==bw)canvas.width=bw;if(canvas.height!==bh)canvas.height=bh;
 canvas.dataset.logicalWidth=w;canvas.dataset.logicalHeight=h;
 const ctx=canvas.getContext('2d'),e=g.expedition,c=e.region,s=e.state,p=g.player.model.position,view=mapViewport(g,w,h,large),{project,scale}=view;
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#10272e';ctx.fillRect(0,0,w,h);
 const [bx,by]=project(view.bounds.min);ctx.fillStyle='#365748';ctx.fillRect(bx,by,(view.bounds.max[0]-view.bounds.min[0])*scale,(view.bounds.max[1]-view.bounds.min[1])*scale);
 const polygon=points=>{points.forEach((q,i)=>{const [x,y]=project(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();};
 const block=(q,width,length,rotation,fill,stroke=null)=>{const [x,y]=project(q);ctx.save();ctx.translate(x,y);ctx.rotate(-rotation);ctx.fillStyle=fill;ctx.fillRect(-width*scale/2,-length*scale/2,width*scale,length*scale);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.strokeRect(-width*scale/2,-length*scale/2,width*scale,length*scale);}ctx.restore();};
 for(const shelf of c.terrain?.shelves||[]){ctx.fillStyle=shelf.height<0?'#1e353b':'#566966';ctx.beginPath();polygon(shelf.polygon);ctx.fill();}
 for(const structure of c.structures||[])if(structure.kind==='floor')block([structure.position[0],structure.position[2]],structure.size[0],structure.size[2],structure.rotation||0,'#50696e');
 for(const water of c.waterBodies||[]){ctx.fillStyle=water.kind==='lava'?'#bc5939':water.kind==='ice'?'#a4d3dc':'#277c9c';ctx.strokeStyle=water.kind==='lava'?'#ffb375':water.kind==='ice'?'#d8f7f4':'#65b7ce';ctx.lineWidth=1.4;ctx.beginPath();for(const points of [water.polygon,...water.holes||[]])polygon(points);ctx.fill('evenodd');ctx.stroke();}
 ctx.lineCap='round';ctx.lineJoin='round';
 for(const path of c.paths||[]){ctx.beginPath();path.points.forEach((q,i)=>{const [x,y]=project(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});const width=Math.max(2.6,path.width*scale*.72);ctx.strokeStyle='#193b3c';ctx.lineWidth=width+2.4;ctx.stroke();ctx.strokeStyle='#ddcf9d';ctx.lineWidth=width;ctx.stroke();}
 for(const prop of c.props||[])if(prop.walkSurface?.kind==='bridge-deck'){const deck=prop.walkSurface;block([prop.x,prop.z],deck.width,deck.length,deck.rotation??prop.rotation??0,'#e4c283','#423b30');}
 for(const structure of c.structures||[])if(['wall','cliff','door'].includes(structure.kind)){
  if(structure.kind==='door'&&g.world.gates?.find(gate=>gate.spec.id===structure.id)?.collider.disabled)continue;
  block([structure.position[0],structure.position[2]],Math.max(.6,structure.size[0]),Math.max(.6,structure.size[2]),structure.rotation||0,structure.kind==='door'?'#f28e75':'#83918a','#193139');
 }
 const marker=(q,color,kind,name='',edge=false)=>{
  let [x,y]=project(q);const outside=x<13||x>w-13||y<13||y>h-13;if(outside&&!edge)return;
  if(outside){const dx=x-w/2,dy=y-h/2,factor=Math.min((w/2-14)/Math.max(.001,Math.abs(dx)),(h/2-14)/Math.max(.001,Math.abs(dy)));x=w/2+dx*factor;y=h/2+dy*factor;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));ctx.fillStyle='#152d34';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.strokeStyle='#12272d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(-5,-6);ctx.lineTo(-2,0);ctx.lineTo(-5,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();return;}
  const r=kind==='landmark'?3:kind==='goal'?8:7;
  ctx.save();ctx.translate(x,y);ctx.fillStyle='#10272f';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();
  if(kind==='goal'){ctx.moveTo(0,-r-2);ctx.lineTo(r+2,0);ctx.lineTo(0,r+2);ctx.lineTo(-r-2,0);ctx.closePath();}else ctx.arc(0,0,r+2,0,Math.PI*2);
  ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.strokeStyle=color;ctx.lineWidth=2.2;
  if(kind==='heal'){ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(4,0);ctx.moveTo(0,-4);ctx.lineTo(0,4);ctx.stroke();}
  else if(kind==='save'){ctx.strokeRect(-4,-5,8,10);ctx.beginPath();ctx.moveTo(-2,-2);ctx.lineTo(2,-2);ctx.moveTo(-2,1);ctx.lineTo(2,1);ctx.stroke();}else if(kind==='water'){ctx.beginPath();ctx.moveTo(0,-6);ctx.bezierCurveTo(-2,-2,-5,0,-4,3);ctx.bezierCurveTo(-2,7,4,6,4,2);ctx.bezierCurveTo(4,0,1,-4,0,-6);ctx.fill();}
  else if(kind==='exit'){ctx.beginPath();ctx.moveTo(-4,4);ctx.lineTo(4,-4);ctx.moveTo(-1,-4);ctx.lineTo(4,-4);ctx.lineTo(4,1);ctx.stroke();}
  else if(kind==='goal'){ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(4,0);ctx.lineTo(0,4);ctx.lineTo(-4,0);ctx.closePath();ctx.fill();}
  else if(kind==='boss'){ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText('!',0,5);}
  else{ctx.beginPath();ctx.arc(0,0,kind==='food'?4:2,0,Math.PI*2);ctx.fill();}
  ctx.restore();
  if(large&&name){ctx.font='bold 12px "Malgun Gothic",sans-serif';ctx.textAlign=x>w*.7?'right':x<w*.3?'left':'center';ctx.strokeStyle='#10272f';ctx.lineWidth=3;ctx.fillStyle=color;const lx=Math.max(12,Math.min(w-12,x)),ly=Math.max(15,y-14);ctx.strokeText(name,lx,ly,w-24);ctx.fillText(name,lx,ly,w-24);}
 };
 ctx.fillStyle='#10272f';ctx.fillRect(5,4,19,19);ctx.fillStyle='#f0f3da';ctx.textAlign='center';ctx.font='bold 12px sans-serif';ctx.fillText('N',14,18);
 const units=large?20:10;ctx.strokeStyle='#eff4da';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(10,h-11);ctx.lineTo(10+units*scale,h-11);ctx.stroke();ctx.textAlign='left';ctx.font='10px sans-serif';ctx.strokeStyle='#10272f';ctx.lineWidth=3;ctx.strokeText(units+' m',10,h-17);ctx.fillStyle='#eff4da';ctx.fillText(units+' m',10,h-17);
 for(const l of c.landmarks||[])if(s.landmarks.includes(l.id))marker([l.position.x,l.position.z],'#bcd2c2','landmark',worldText(l.name));
 const safe=c.safePoint;if(s.safePoints.includes(safe.id))marker([safe.position.x,safe.position.z],'#9cf2ae','heal',large?worldText(safe.name):'');
 for(const i of g.world.interactions||[])if(i.kind==='save')marker([i.x,i.z],'#ffe3a1','save',large?'탐험 기록 저장대':'');else if(i.kind==='drink'&&g.save.survival.provisions.sources[i.sourceId]?.discovered)marker([i.x,i.z],g.save.survival.provisions.sources[i.sourceId]?.unlocked?'#78dfff':'#bfa277','water',large?(supplies.WATER_SOURCES.find(s=>s.id===i.sourceId)?.name+' '+(g.save.survival.provisions.sources[i.sourceId]?.unlocked?'':'(해금 필요)')):'');else if(i.kind==='food')marker([i.x,i.z],'#ffbc7a','food',large?t('survival.mapFood'):'');
 for(const exit of c.entrances||[]){const known=s.exits.includes(g.save.region+':'+exit.to)||g.save.discovered.includes(exit.to);marker([exit.position.x,exit.position.z],g.canTravel(exit.to)?'#b2ebcb':'#f3a58f','exit',large&&known?g.biomeById.get(exit.to)?.name:'');}
 for(const i of g.world.interactions||[])if(i.kind==='special'&&i.acquisition.kind==='boss'&&s.landmarks.includes(c.specialBindings.find(b=>b.speciesId===i.acquisition.speciesId)?.landmarkId))marker([i.x,i.z],'#efa4ef','boss');
 const goal=e.objective();if(goal.point)marker([goal.point.x,goal.point.z],'#ffe17c','goal',large?goal.name:'',!large);
 const [px,py]=project([p.x,p.z]);ctx.save();ctx.translate(px,py);ctx.fillStyle='#133842';ctx.strokeStyle='#6fefff';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.rotate(-g.player.model.rotation.y);ctx.fillStyle='#ffffff';ctx.strokeStyle='#164a53';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(0,8);ctx.lineTo(-6,-6);ctx.lineTo(0,-3);ctx.lineTo(6,-6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
 canvas.dataset.player=p.x.toFixed(1)+','+p.z.toFixed(1);canvas.dataset.playerScreen=px.toFixed(1)+','+py.toFixed(1);canvas.dataset.mapScale=String(scale);canvas.dataset.zoom=String(view.zoom);canvas.dataset.goal=goal.name;canvas.dataset.discoveredLandmarks=String(s.landmarks.length);canvas.dataset.drinkSpots=String((g.world.interactions||[]).filter(i=>i.kind==='drink'&&g.save.survival.provisions.sources[i.sourceId]?.discovered).length);canvas.dataset.foodDrops=String((g.world.interactions||[]).filter(i=>i.kind==='food').length);
}
export function updateNavigation(ui){const g=ui.game,e=g.expedition;if(!e||!g.player)return;let mini=document.querySelector('#minimap');
 if(!mini){document.querySelector('#hud').insertAdjacentHTML('beforeend','<div class="minimap-wrap"><div class="minimap-heading"><strong id="minimap-title"></strong><div class="minimap-controls"><button id="minimap-less">−</button><button id="minimap-more">+</button></div></div><canvas id="minimap" width="220" height="220"></canvas><div class="minimap-legend"><span><i class="mini-you"></i><b data-mini-label="player"></b></span><span><i class="mini-goal"></i><b data-mini-label="goal"></b></span><span><i class="mini-heal">+</i><b data-mini-label="heal"></b></span><span><i class="mini-water"></i><b data-mini-label="water"></b></span></div><div class="minimap-save-key">▣ 저장대</div><div class="minimap-footer"><button id="minimap-open"></button></div></div><div id="compass" class="compass"></div><div id="tutorial-hint" class="tutorial-hint"></div>');mini=document.querySelector('#minimap');document.querySelector('.minimap-footer').prepend(document.querySelector('#region-name'));document.querySelector('#minimap-open').onclick=()=>g.openPanel('map');for(const [id,delta] of [['minimap-less',-.35],['minimap-more',.35]])document.querySelector('#'+id).onclick=()=>{g.minimapZoom=Math.max(1,Math.min(3,Math.round(((g.minimapZoom??1.35)+delta)*100)/100));drawMap(mini,g);};}
 const mapButton=document.querySelector('#minimap-open');mapButton.textContent='M ↗';mapButton.title='M · '+t('minimap.full');mapButton.setAttribute('aria-label',t('minimap.full'));document.querySelector('#region-name').title=g.biomeById.get(g.save.region).name;document.querySelector('#minimap-title').textContent=t('minimap.nearby');document.querySelector('#minimap-title').title=g.biomeById.get(g.save.region).name;mini.setAttribute('aria-label',t('minimap.aria',{region:g.biomeById.get(g.save.region).name}));for(const key of ['player','goal','heal','water'])document.querySelector('[data-mini-label="'+key+'"]').textContent=t('minimap.'+key);
 for(const [id,key,disabled] of [['minimap-less','out',(g.minimapZoom??1.35)<=1],['minimap-more','in',(g.minimapZoom??1.35)>=3]]){const button=document.querySelector('#'+id);button.setAttribute('aria-label',t('minimap.zoom'+key));button.title=t('minimap.zoom'+key);button.disabled=disabled;}
 drawMap(mini,g);if(g.panel==='map')drawMap(document.querySelector('#atlas-canvas'),g,true);const goal=e.objective(),count=caughtCount(g.save),next=MILESTONES.find(n=>n>count)||151,local=[...new Set(g.biomeById.get(g.save.region).spawnTable.map(s=>s.speciesId))],unknown=local.filter(id=>!g.save.dex[id]?.caught).length;const stamp=[goal.name,goal.description,count,unknown,currentLocale()].join('|');const goalChanged=ui.objectiveStamp!==stamp;if(goalChanged){ui.objectiveStamp=stamp;document.querySelector('#objective').innerHTML=`<span class="eyebrow">${t('exp.next')}</span><b>${esc(goal.name)}</b><p>${esc(goal.description)}</p><small>${t('exp.nextMilestone',{count,goal:next})}</small><small>${t('exp.localResearch',{percent:local.length?Math.round((local.length-unknown)/local.length*100):100,unknown})}</small>`;}
 const compass=document.querySelector('#compass');if(goal.point){const dx=goal.point.x-g.player.model.position.x,dz=goal.point.z-g.player.model.position.z,angle=Math.atan2(dx,dz)-g.world.orbit.yaw;compass.innerHTML=`<span style="display:inline-block;transform:rotate(${-angle*180/Math.PI}deg)">↑</span> ${esc(t('exp.distance',{name:goal.name,distance:Math.round(Math.hypot(dx,dz))}))}`;}else compass.textContent=goal.name;
 const objective=document.querySelector('#objective');if(goalChanged&&goal.point){objective.insertAdjacentHTML('beforeend',`<button id="walk-goal">${t('exp.walkGoal')} ↗</button>`);document.querySelector('#walk-goal').onclick=()=>g.walkTo(goal.point);}
 const tutorial=document.querySelector('#tutorial-hint');tutorial.textContent=e.tutorial();tutorial.classList.toggle('hidden',!tutorial.textContent||!!g.panel);mini.closest('.minimap-wrap').classList.toggle('hidden',!!g.panel);
}
