import {caughtCount,requirementsMet,ITEMS} from './core.mjs';
const milestones=[5,10,20,30,50,75,100,125,150,151];
const label=x=>typeof x==='string'?x:x?.['ko-KR']||x?.ko||'';
function route(game,destination){const queue=[[game.save.region]],seen=new Set();while(queue.length){const path=queue.shift(),last=path.at(-1);if(last===destination)return path;if(seen.has(last))continue;seen.add(last);for(const id of game.biomeById.get(last)?.connections||[])if(!seen.has(id))queue.push([...path,id]);}return [];}
export function recommendObjective(game){const save=game.save,e=game.expedition,count=caughtCount(save),candidates=[],add=(goal,stack=new Set())=>{
 if(stack.has(goal.id))return;stack=new Set([...stack,goal.id]);const path=route(game,goal.region||save.region);if(!path.length)return;const blocked=path.slice(1).find(id=>!save.discovered.includes(id)&&!game.canTravel(id));if(blocked&&goal.id!=='region:'+blocked){const b=game.biomeById.get(blocked);add({id:'region:'+blocked,name:b.name+' 탐험로',region:blocked,required:b.requirements.caughtCount||0,requirements:b.requirements,benefit:b.name+' 지역 개방'},stack);return;}
 const req=goal.requirements||{};for(const boss of req.bosses||[])if(!save.bosses.includes(boss)){for(const b of game.biomes){const encounter=b.specialEncounters.find(x=>x.speciesId===boss);if(encounter)add(specialGoal(b,encounter),stack);}return;}
 if(req.item&&!save.inventory[req.item]){if(req.item==='fishing-rod'){const price=ITEMS['fishing-rod'].price;if(save.coins>=price){const point=game.compositions.regions.verdant.services.shop;add({id:'item:fishing-rod',name:'낚싯대 준비하기',region:'verdant',point:{x:point[0],z:point[1]},required:0,benefit:`보급 수레에서 낚싯대 구매 · ${save.coins} / ${price} 연구 자금 · 낚시 포켓몬을 만날 준비`},stack);}else{const pickup=game.world.interactions?.find(i=>i.kind==='pickup'&&!(i.usedUntil>save.playTime));add({id:'funds:fishing-rod',name:'낚싯대 준비 자금 모으기',region:save.region,point:pickup?{x:pickup.x,z:pickup.z}:null,required:0,benefit:`현재 ${save.coins} / ${price} 연구 자금 · 보급품 수집·전투로 ${price-save.coins} 모으기`},stack);}return;}for(const [id,r] of Object.entries(game.compositions.regions)){const site=(r.digSites||[]).find(s=>s.item===req.item);if(site){add({id:'item:'+req.item,name:label(site.name)||'복원용 화석 발굴',region:id,point:{x:site.position[0],z:site.position[1]},required:game.biomeById.get(id).requirements.caughtCount||0,benefit:game.byId.get(goal.speciesId)?.name+' 복원에 필요한 화석',item:req.item},stack);return;}}return;}
 if(goal.speciesId===151&&!save.flags['mew-puzzle']){add({id:'puzzle:mew',name:'기억의 돌 순서 맞추기',region:'complex',required:150,requirements:{bosses:[150]},point:{x:-10,z:-18},benefit:'뮤를 만날 준비 · 돌의 기록을 순서대로 활성화'},stack);return;}
 if(req.flag&&!save.flags[req.flag])return;
 const required=Math.max(goal.required||0,...path.filter(id=>!save.discovered.includes(id)).map(id=>game.biomeById.get(id).requirements.caughtCount||0)),additional=Math.max(0,required-count),here=goal.region===save.region;
 let point=goal.point;if(!here){const exit=e.routeExit(goal.region);point=exit?.position;}else if(!point&&goal.speciesId){const r=game.compositions.regions[goal.region],binding=r.specialBindings?.find(b=>b.speciesId===goal.speciesId);if(binding){const l=r.landmarks.find(l=>l.id===binding.landmarkId);point=l?.interactionPosition||l?.position;}if(!point){const pocket=r.ecologyPockets.find(p=>p.speciesIds.includes(goal.speciesId));if(pocket)point={x:pocket.center[0],z:pocket.center[1]};}}
 const rawTime=req.time||goal.time,rawWeather=req.weather||goal.weather,time=['day','night'].includes(rawTime)?rawTime:null,weather=rawWeather&&rawWeather!=='any'?rawWeather:null,condition=(time?' · '+(time==='night'?'밤':'낮')+'에 출현':'')+(weather?' · 날씨 '+({clear:'맑음',rain:'비',mist:'안개'}[weather]||weather):'');candidates.push({...goal,required,additional,point,here,description:`도감 ${count} / ${required}종 · 추가 ${additional}종. ${goal.benefit||''}${condition}${!here?' · '+game.biomeById.get(goal.region).name+'로 이동':''}`});
 },specialGoal=(b,s)=>({id:'encounter:'+s.speciesId,name:game.byId.get(s.speciesId).name+(s.kind==='boss'?' 성역 도전':' 만나기'),speciesId:s.speciesId,region:b.id,requirements:s.requirements,required:s.requirements.caughtCount||0,benefit:game.byId.get(s.speciesId).name+'를 동료로 맞이할 기회'});
 for(const n of milestones)if(!e.state.claimedMilestones.includes(n))add({id:'milestone:'+String(n).padStart(3,'0'),name:n+'종 도감 연구 보상',region:save.region,required:n,benefit:`${n>=50?'하이퍼볼·':''}슈퍼볼·이상한사탕·연구 자금 보상`});
 for(const b of game.biomes){if(!save.discovered.includes(b.id))add({id:'region:'+b.id,name:b.name+' 탐험로',region:b.id,requirements:b.requirements,required:b.requirements.caughtCount||0,benefit:b.name+' 개방 · '+[...new Set(b.spawnTable.map(s=>s.speciesId))].slice(0,3).map(id=>game.byId.get(id).name).join('·')+' 서식지'});
 for(const s of b.specialEncounters)if(!save.dex[s.speciesId]?.caught&&!(s.kind==='boss'&&save.bosses.includes(s.speciesId)))add(specialGoal(b,s));
 for(const entry of b.spawnTable)if(!save.dex[entry.speciesId]?.caught&&(entry.requirements?.caughtCount||0)>0)add({id:'habitat:'+b.id+':'+entry.speciesId,name:game.byId.get(entry.speciesId).name+' 서식지',speciesId:entry.speciesId,region:b.id,requirements:{...entry.requirements,...(entry.method==='fishing'?{item:'fishing-rod'}:{})},required:entry.requirements.caughtCount||0,time:entry.time,weather:entry.weather,benefit:game.byId.get(entry.speciesId).name+' 출현 조건 달성'});}
 const unique=[...new Map(candidates.map(g=>[g.id,g])).values()];unique.sort((a,b)=>a.additional-b.additional||Number(b.here)-Number(a.here)||a.required-b.required||a.id.localeCompare(b.id));return unique[0]||{id:'complete',name:'151종 탐험 기록 완성',required:151,additional:0,description:'모든 수집 목표를 달성했어요. 남은 명소와 친구들을 자유롭게 찾아보세요.',point:null};
}
