import {WATER_SOURCES,APPLE_TREES} from './supplies.mjs';
import {THREE} from './world.mjs';
import {liquidMesh,waterfallMesh} from './liquid-material.mjs';
import {buildStructures} from './structures.mjs';
import {terrainMaterial} from './terrain-material.mjs';
import {currentLocale,t,tx} from './i18n.mjs';
const label=x=>x?.[currentLocale()]||x?.['en-US']||'';
export function insidePolygon(x,z,points=[]){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
export function waterAt(world,x,z){return world.composition?.waterBodies.find(b=>insidePolygon(x,z,b.polygon)&&!(b.holes||[]).some(h=>insidePolygon(x,z,h.polygon||h)))||null;}
function distanceToPath(x,z,path){let best=1e6;for(let i=1;i<path.points.length;i++){const a=path.points[i-1],b=path.points[i],dx=b[0]-a[0],dz=b[1]-a[1],f=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz)));best=Math.min(best,Math.hypot(x-a[0]-dx*f,z-a[1]-dz*f));}return best;}
export function pathAt(world,x,z){return world.composition?.paths.find(p=>distanceToPath(x,z,p)<p.width*.5);}
export function regionHeight(world,x,z,walk=true){const c=world.composition;if(!c)return 0;let h=(Math.sin(x*.055)*Math.cos(z*.06)+Math.sin(z*.09)*.25)*c.terrain.baseAmplitude;
 for(const f of c.terrain.features){const dx=x-f.center[0],dz=z-f.center[1],co=Math.cos(f.rotation||0),si=Math.sin(f.rotation||0),d=Math.hypot((dx*co+dz*si)/f.radius[0],(-dx*si+dz*co)/f.radius[1]);h+=f.height*(f.shape==='plateau'?Math.max(0,Math.min(1,(1-d)/.45)):Math.exp(-(f.falloff||2.4)*d*d));}
 for(const shelf of c.terrain.shelves||[])if(insidePolygon(x,z,shelf.polygon))h=shelf.height;
 for(const ramp of c.terrain.ramps||[]){const [a,b]=ramp.points,dx=b[0]-a[0],dz=b[1]-a[1],t=((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz);if(t>=0&&t<=1&&Math.hypot(x-a[0]-dx*t,z-a[1]-dz*t)<ramp.width/2)h=ramp.heights[0]+(ramp.heights[1]-ramp.heights[0])*t;}
 for(const body of c.waterBodies){const points=[body.polygon,...(body.holes||[]).map(h=>h.polygon||h)];let edge=Infinity;for(const polygon of points){const loop={points:[...polygon,polygon[0]]};edge=Math.min(edge,distanceToPath(x,z,loop));}const wet=waterAt(world,x,z)===body,width=body.basin?.shoreBlendWidth||2.5,f=Math.min(1,edge/width),blend=f*f*(3-2*f);if(wet)h=body.surfaceY-.04+((body.basin?.floorY??body.surfaceY-.8)-(body.surfaceY-.04))*blend;else if(edge<width)h=(body.surfaceY+.04)*(1-blend)+h*blend;if(walk&&wet&&body.kind==='ice')h=body.surfaceY+.025;}
 for(const surface of (world.walkSurfaces||[])){const dx=x-surface.x,dz=z-surface.z,co=Math.cos(surface.rotation),si=Math.sin(surface.rotation),u=Math.abs(dx*co-dz*si),v=Math.abs(dx*si+dz*co),outside=Math.max(u-surface.width/2,v-surface.length/2);if(outside<=1e-6){if(walk)h=Math.max(h,surface.y);else if(surface.kind==='bridge-deck')h=Math.min(h,surface.y-.04);}else if(outside<surface.blend&&(surface.kind!=='bridge-deck'||u<=surface.width/2+1e-6))h=Math.max(h,h+(surface.y-h)*(1-outside/surface.blend));}
 return h;
}
export async function buildRegion(world,biome,onProgress=()=>{}){
 world.clearLevel();world.region=biome.id;world.biome=biome;const c=world.compositions.regions[biome.id];world.composition=c;world.walkSurfaces=[];world.palette=c.palette;world.scene.fog=new THREE.FogExp2(c.palette.fog,biome.id==='cave'?.018:biome.id==='ruins'?.014:.0065);world.sky.material.uniforms.top.value.set(c.palette.sky);world.sky.material.uniforms.bottom.value.set(c.palette.fog);world.scene.background.set(c.palette.fog);
 world.ownedMaterials=[];world.placementRecords=[];world.canopyColor=new THREE.Color(c.palette.canopy);const batches=new Map();
 const add=(path,p)=>{const key=path+'|'+(p.materialVariant||'');if(!batches.has(key))batches.set(key,{path,placements:[]});batches.get(key).placements.push(p);};
 for(const p of c.props){add(p.rendererKey,p);if(p.collision&&!p.rendererKey.includes('wall')){const size=p.bounds;world.colliders.push({prop:p,x:p.x,z:p.z,r:p.collision.radius||Math.min(size.width,size.depth)*.4,h:size.height,cameraRadius:Math.min(size.width,size.depth)*.42});}}
 for(const p of c.props)if(p.walkSurface){p.resolvedBaseY=regionHeight(world,p.x,p.z,false)+(p.y||0);if(p.walkSurface.kind==='bridge-deck'){const half=p.walkSurface.length/2,dx=Math.sin(p.walkSurface.rotation??p.rotation??0)*half,dz=Math.cos(p.walkSurface.rotation??p.rotation??0)*half,body=waterAt(world,p.x,p.z);const deck=Math.max(regionHeight(world,p.x-dx,p.z-dz,false),regionHeight(world,p.x+dx,p.z+dz,false),body?body.surfaceY+.2:-Infinity);p.resolvedBaseY=deck-p.bounds.height*p.walkSurface.heightFraction;}world.walkSurfaces.push({kind:p.walkSurface.kind,x:p.x,z:p.z,rotation:p.walkSurface.rotation??p.rotation??0,width:p.walkSurface.width,length:p.walkSurface.length,y:p.resolvedBaseY+p.bounds.height*p.walkSurface.heightFraction,blend:p.walkSurface.approachBlendLength||2});}
 for(const p of c.props)if(p.walkSurface?.rails){const r=p.walkSurface.rotation??p.rotation??0,y=p.resolvedBaseY+p.bounds.height*p.walkSurface.heightFraction;for(const side of [-1,1])world.colliders.push({type:'obb',x:p.x+Math.cos(r)*p.walkSurface.rails*side,z:p.z-Math.sin(r)*p.walkSurface.rails*side,rotation:r,halfWidth:.15,halfDepth:p.walkSurface.length/2,h:.7,bottomY:y,topY:y+.7,r:.15});}
 buildStructures(world,c);
 const extent=c.staged===false?c.playableBounds.max[0]*2+12:150;const terrain=new THREE.PlaneGeometry(extent,extent,120,120);terrain.rotateX(-Math.PI/2);const a=terrain.attributes.position;
 for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i);a.setY(i,regionHeight(world,x,z,false));}
 terrain.computeVertexNormals();const ground=world.owned(new THREE.Mesh(terrain,terrainMaterial(c)));ground.receiveShadow=true;world.ground=ground;
 // Explicit approach strips keep the rendered bank aligned with the walk surface
 // between the coarse terrain grid and the measured GLB deck edge.
 for(const surface of world.walkSurfaces.filter(s=>s.kind==='bridge-deck'))for(const sign of [-1,1]){const vertices=[],indices=[],r=surface.rotation,co=Math.cos(r),si=Math.sin(r),n=16;for(let j=0;j<=n;j++){const v=sign*(surface.length/2+surface.blend*(1-j/n));for(const side of [-1,1]){const u=side*surface.width/2,x=surface.x+u*co+v*si,z=surface.z-u*si+v*co;vertices.push(x,regionHeight(world,x,z,true)+.005,z);}if(j<n){const k=j*2;indices.push(k,k+2,k+1,k+1,k+2,k+3);}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();const material=terrainMaterial(c);material.side=THREE.DoubleSide;const mesh=world.owned(new THREE.Mesh(geometry,material));mesh.userData.walkApproach=true;mesh.receiveShadow=true;}
 // Dressing is constrained to authored ecology pockets and clear paths. Skyline,
 // major structures, water and elevation all come from measured compositions.
 for(const [pi,pocket] of c.ecologyPockets.entries()){if(pocket.indoor||pocket.method==='fishing'||biome.id==='laboratory')continue;for(let i=0;i<35;i++){const angle=i*2.399963,r=Math.sqrt((i+.5)/35),x=pocket.center[0]+Math.cos(angle)*r*pocket.radius[0],z=pocket.center[1]+Math.sin(angle)*r*pocket.radius[1];if(pathAt(world,x,z)||waterAt(world,x,z)||Math.hypot(x,z)<4)continue;const path=biome.id==='highlands'?(pocket.id.includes('cave')?'quaternius/Mushroom_Common':pocket.id.includes('snow')?'quaternius/Pebble_Round_5':'quaternius/Pebble_Square_3'):['volcano','caldera'].includes(biome.id)?'quaternius/Pebble_Square_3':biome.id==='cave'?'quaternius/Mushroom_Common':biome.id==='laboratory'?'survival/box-large':biome.id==='frozen'?'quaternius/Pebble_Round_5':i%5===0?'quaternius/Fern_1':'quaternius/Grass_Common_Short';add(path,{x,z,height:biome.id==='laboratory'?.35:.25+(i%4)*.12,rotation:angle,materialVariant:biome.id});}}
 world.liquidLight={value:1};for(const body of c.waterBodies)world.owned(liquidMesh(body,c.palette,world.wind,world.liquidLight));
 // A local, readable rest marker replaces the identical orange tent in every area.
 const marker=(kind,name,x,z,data={})=>{const item={kind,x,z,...data};Object.defineProperty(item,'name',{enumerable:true,get:()=>item.landmark?label(item.landmark.name):item.shortcut?label(item.shortcut.name):tx(name)});world.interactions.push(item);};const safe=c.safePoint.position;
 marker('heal',t('interaction.restTrail'),safe.x,safe.z,{safeId:c.safePoint.id});world.addBeacon(safe.x,safe.z,0xade3b4);world.addStationSign(safe.x,safe.z,0xb9f5b4,'heal');
 if(!c.props.some(p=>/campfire/.test(p.rendererKey)&&Math.hypot(p.x-safe.x,p.z-safe.z)<8))add('survival/campfire-pit',{x:safe.x-2.2,z:safe.z-1.6,height:.8,rotation:.3});if(!c.props.some(p=>/bedroll/.test(p.rendererKey)&&Math.hypot(p.x-safe.x,p.z-safe.z)<8))add('survival/bedroll',{x:safe.x+2.2,z:safe.z-1.8,height:.65,rotation:.4});
 const clearCampPoint=(offsets)=>offsets.map(([dx,dz])=>[safe.x+dx,safe.z+dz]).find(([x,z])=>{const [cx,cz]=world.collision(x,z,.55);return Math.hypot(cx-x,cz-z)<.01&&!waterAt(world,x,z)&&Math.abs(world.height(x,z)-world.height(safe.x,safe.z))<1.5;});
 const savePoint=clearCampPoint([[3,0],[-3,0],[0,3],[2,2],[-2,2]])||[safe.x,safe.z];marker('save','탐험 기록 저장대',...savePoint,{safeId:c.safePoint.id});world.addStationSign(...savePoint,0xffe3a1,'save');add('survival/workbench',{x:savePoint[0],z:savePoint[1],height:.9,rotation:0});
 const campPoint=clearCampPoint([[-3,0],[0,3],[3,3],[-3,3]])||[safe.x,safe.z];marker('camp','친구들의 쉼터',...campPoint);world.addStationSign(...campPoint,0xc7b9ff,'camp');
 const signFor=(x,z,color,kind)=>{const first=world.level.children.length;world.addStationSign(x,z,color,kind);return world.level.children.slice(first);};
 const rationPoint=clearCampPoint([[0,5],[4,4],[-4,4],[0,6]])||[safe.x,safe.z];marker('rations','캠프 기본 식량',...rationPoint,{signs:signFor(...rationPoint,0xe5cc88,'food')});add('survival/box-large',{x:rationPoint[0],z:rationPoint[1],height:.55,rotation:.2});
 for(const source of WATER_SOURCES.filter(s=>s.region===biome.id)){const {x,z}=source;marker('drink',source.name,x,z,{sourceId:source.id,signs:signFor(x,z,0x91eafb,'drink')});add('survival/barrel',{x,z,height:1.3,rotation:.5});world.addBeacon(x,z,0x78d8ee);}
 for(const tree of APPLE_TREES.filter(t=>t.region===biome.id)){const prop=c.props[tree.prop];if(!prop)throw Error('Missing authored apple tree '+tree.id);const candidates=[];for(const radius of [2.8,3.4,4])for(let n=0;n<16;n++)candidates.push([prop.x+Math.sin(n*Math.PI/8)*radius,prop.z+Math.cos(n*Math.PI/8)*radius]);const point=candidates.find(([x,z])=>{const [cx,cz]=world.collision(x,z,.55);return Math.hypot(cx-x,cz-z)<.01&&!waterAt(world,x,z)&&Math.abs(world.height(x,z)-world.height(prop.x,prop.z))<1.5;});if(!point)throw Error('No apple gathering position '+tree.id);const fruits=[];for(const [dx,dz,dy] of [[-.5,0,0],[.5,.2,.4],[0,-.5,.8]]){const mesh=world.owned(new THREE.Mesh(new THREE.DodecahedronGeometry(.22,0),new THREE.MeshStandardMaterial({color:0xe96559,emissive:0x7c3020,emissiveIntensity:.35})));mesh.position.set(prop.x+dx,world.height(prop.x,prop.z)+2+dy,prop.z+dz);fruits.push(mesh);}marker('apple-tree','사과나무',...point,{treeId:tree.id,fruits,signs:signFor(...point,0xef997b,'food')});}
 if(biome.id==='camp'||c.services){const research=c.services?.research?{x:c.services.research[0],z:c.services.research[1]}:c.landmarks[0].position,supplies=c.services?.shop?{x:c.services.shop[0],z:c.services.shop[1]}:c.landmarks[2].position;marker('research',t('panel.research'),research.x,research.z);marker('shop',t('panel.shop'),supplies.x,supplies.z);marker('mapboard',label({'ko-KR':'탐험 안내판','en-US':'Expedition route board'}),...(c.services?.board||[0,4]));add('nature/sign',{x:c.services?.board?.[0]||0,z:c.services?.board?.[1]||4,height:1.8,rotation:0});}
 for(const l of c.landmarks){marker('landmark',label(l.name),(l.interactionPosition||l.position).x,(l.interactionPosition||l.position).z,{landmark:l});world.addBeacon(l.position.x,l.position.z,c.palette.accent);}
 for(const entrance of c.entrances){const p=entrance.position;marker('travel',t('interaction.followTrail'),p.x,p.z,{to:entrance.to});world.addBeacon(p.x,p.z,0xc4ecbf);}
 for(const [i,s] of (biome.specialEncounters||[]).entries()){if(c.pendingSpecies?.includes(s.speciesId))continue;const binding=c.specialBindings.find(b=>b.speciesId===s.speciesId),position=binding?.position||[18+i*8,-18];marker('special',s.kind==='boss'?t('boss.sanctuary'):t('panel.research'),...position,{acquisition:s});world.addBeacon(...position,s.kind==='boss'?0xd4aff7:0xf0d79b);}
 for(const [i,s] of biome.spawnTable.filter(s=>['nest','tree'].includes(s.method)&&!c.pendingSpecies?.includes(s.speciesId)).entries()){const pocket=c.ecologyPockets.find(p=>p.speciesIds.includes(s.speciesId)&&p.method===s.method),base=pocket?.center||[8+i*6,18],radius=pocket?Math.min(2+i%3*1.5,Math.min(...pocket.radius)*.65):2+i%3*1.5,p=[base[0]+Math.cos(i*2.4)*radius,base[1]+Math.sin(i*2.4)*radius];marker(s.method,t(s.method==='tree'?'interaction.shakeTree':'interaction.inspectNest'),p[0],p[1],{entry:s});world.addBeacon(p[0],p[1],0xd4e7ac);add(pocket?.indoor?'survival/chest':s.method==='tree'?'quaternius/CommonTree_1':'quaternius/Bush_Common',{x:p[0],z:p[1],y:pocket?.indoor?.1:0,height:pocket?.indoor?.6:s.method==='tree'?5:1.1,rotation:i});}
 if(c.waterBodies.some(b=>b.kind!=='lava')&&biome.spawnTable.some(s=>s.method==='fishing')){const pier=c.fishingPoint||c.landmarks.find(l=>/pier|tide|water|pool/.test(l.id))?.position||{x:safe.x-4,z:safe.z-4};marker('fishing',t('interaction.fishing'),pier.x,pier.z);}
 for(const site of c.digSites||[]){marker('dig',t('interaction.dig'),...site.position,{item:site.item});world.addBeacon(...site.position,0xe5d6a5);}
 if(['mountain','cave','coast'].includes(biome.id)){const p=c.landmarks.at(-1).position;marker('dig',t('interaction.dig'),p.x+4,p.z+2);world.addBeacon(p.x+4,p.z+2,0xe5d6a5);}
 if(biome.id==='ruins'||biome.id==='complex')(c.setpieces.find(s=>s.kind==='rune-interactions')?.positions||[[-10,-18],[0,-30],[10,-18]]).forEach(([x,z],i)=>{marker('rune',label({'ko-KR':`기억의 돌 ${i+1}`,'en-US':`Memory stone ${i+1}`}),x,z,{rune:i});world.addBeacon(x,z,0xd6b6ef);world.addStationSign(x,z,0xd6b6ef,'activate');});
 if(c.labDoor)marker('door',t('exp.labDoor'),...c.labDoor.interaction,{door:c.labDoor});
 for(const shortcut of world.compositions.shortcuts.filter(s=>s.regionId===biome.id)){marker('capability',label(shortcut.name),...shortcut.interaction,{shortcut});if(['climb','surf'].includes(shortcut.capability))marker('capability',label(shortcut.name),...shortcut.to,{shortcut});world.addBeacon(...shortcut.interaction,0xe9cb84);world.addStationSign(...shortcut.interaction,0xe9cb84,'activate');}
 for(const [i,l] of c.landmarks.entries()){const p=l.position,key=c.staged===false?l.id:`${biome.id}-landmark-${i}`;marker('pickup',t('interaction.pickup'),p.x+3,p.z+3,{key});add('survival/chest',{x:p.x+3,z:p.z+3,height:.5,rotation:.5,pickupKey:key});}
 let done=0;for(const batch of batches.values()){await placeComposedBatch(world,batch.path,batch.placements);onProgress(++done/batches.size*.9);}
 addSetpieces(world,c);world.addAtmosphere(()=>Math.random(),biome.id);world.cameraTarget.set(safe.x,1,safe.z);onProgress(1);return world;
}
async function placeComposedBatch(world,path,placements){const template=await world.template(path),bounds=template.userData.bounds,size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),sources=[];template.traverse(m=>{if(m.isMesh)sources.push(m);});
 if(path.includes('wall'))for(const p of placements)if(p.collision){const scale=p.scale??(p.height||1)/Math.max(.05,size.y);world.colliders.push({prop:p,type:'obb',x:p.x,z:p.z,rotation:p.rotation||0,halfWidth:size.x*scale/2,halfDepth:size.z*scale/2,h:size.y*scale,r:Math.min(size.x,size.z)*scale*.5,cameraRadius:Math.max(size.x,size.z)*scale*.4});}
 for(const source of sources){const original=source.material,materials=(Array.isArray(original)?original:[original]).map(mat=>{const m=mat.clone(),variant=world.compositions.materialVariants[placements[0].materialVariant];const leaves=/Leaves|Leaf|Pine/i.test(mat.name)&&!!mat.map;
  if(variant?.color)m.color.set(variant.color);else if(variant?.bark&&!leaves)m.color.set(variant.bark);if(variant?.emissive)m.emissive?.set(variant.emissive);if(variant?.roughness!==undefined)m.roughness=variant.roughness;if(variant?.metalness!==undefined)m.metalness=variant.metalness;if(variant?.emissiveIntensity!==undefined)m.emissiveIntensity=variant.emissiveIntensity;
  if(leaves){m.alphaTest=.35;m.roughness=.95;m.color.set(0xffffff);m.onBeforeCompile=shader=>{shader.uniforms.canopy={value:new THREE.Color(variant?.canopy||world.composition.palette.canopy)};shader.fragmentShader='uniform vec3 canopy;\n'+shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb=canopy*(0.68+dot(diffuseColor.rgb,vec3(.2126,.7152,.0722))*.50);');};m.customProgramCacheKey=()=>`regional-canopy-v2-${world.region}`;}
  world.ownedMaterials.push(m);return m;});const inst=new THREE.InstancedMesh(source.geometry,Array.isArray(original)?materials:materials[0],placements.length);inst.userData.shared=true;inst.castShadow=placements.length<50;inst.receiveShadow=true;
  // The existing player-following 64m shadow frustum bounds foliage shadows;
  // low quality disables them with the shared shadow map. No extra draw meshes.
  const transform=new THREE.Object3D(),basis=new THREE.Matrix4(),align=new THREE.Matrix4().makeTranslation(-center.x,-bounds.min.y,-center.z);
  for(const [i,p] of placements.entries()){const scale=p.scale??(p.height||1)/Math.max(.05,size.y),surface=p.surfaceAnchor;let y=surface?.kind==='water'?surface.surfaceY+(surface.offsetY||0):p.resolvedBaseY??regionHeight(world,p.x,p.z,false)+(p.y||0);transform.position.set(p.x,y,p.z);transform.rotation.y=p.rotation||0;transform.scale.set(scale*(p.scaleXYZ?.[0]||1),scale*(p.scaleXYZ?.[1]||1),scale*(p.scaleXYZ?.[2]||1));transform.updateMatrix();basis.copy(transform.matrix).multiply(align).multiply(source.matrixWorld);inst.setMatrixAt(i,basis);world.placementRecords.push({mesh:inst,index:i,path,p});}
  inst.instanceMatrix.needsUpdate=true;inst.computeBoundingSphere();world.level.add(inst);
 }
}
function addSetpieces(world,c){for(const s of c.setpieces||[])if(s.kind==='containment-ring'){const ring=world.owned(new THREE.Mesh(new THREE.RingGeometry(s.radius-.08,s.radius,64),new THREE.MeshBasicMaterial({color:s.color,side:THREE.DoubleSide})));ring.rotation.x=-Math.PI/2;ring.position.set(s.position[0],world.height(...s.position)+.025,s.position[1]);}for(const spec of c.setpieces||[])if(spec.kind==='waterfall-ribbon'){world.owned(waterfallMesh(spec,world.wind));const splash=world.owned(new THREE.Mesh(new THREE.RingGeometry(spec.width*.3,spec.width*.8,32),new THREE.MeshBasicMaterial({color:spec.color,transparent:true,opacity:.45,side:THREE.DoubleSide,depthWrite:false})));splash.rotation.x=-Math.PI/2;splash.position.set(spec.to[0],spec.to[1]+.04,spec.to[2]);}const accent=c.palette.accent;for(const l of c.landmarks){if(l.rank!=='major')continue;const p=l.position,y=world.height(p.x,p.z);if(c.id==='lake'){for(let i=0;i<3;i++){const water=world.owned(new THREE.Mesh(new THREE.PlaneGeometry(1.5,6),new THREE.MeshBasicMaterial({color:0xb8e8ef,transparent:true,opacity:.55,side:THREE.DoubleSide})));water.position.set(p.x+i*1.2-1.2,y+1.8,p.z+2);}}
 if(['powerplant','laboratory'].includes(c.id)){const glow=world.owned(new THREE.Mesh(new THREE.CylinderGeometry(c.id==='laboratory'?4:1.1,c.id==='laboratory'?4:1.1,5,16,true),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.14,side:THREE.DoubleSide})));glow.position.set(p.x,y+2.5,p.z);world.addBeacon(p.x,p.z,accent);}
 if(c.id==='volcano'){for(let i=0;i<6;i++){const crack=world.owned(new THREE.Mesh(new THREE.BoxGeometry(.15,.04,7),new THREE.MeshBasicMaterial({color:0xff783b})));crack.position.set(p.x+Math.sin(i)*5,y+.09,p.z+Math.cos(i)*5);crack.rotation.y=i;}}
 if(c.id==='ruins'){const glow=new THREE.PointLight(0xab81db,3,15);glow.position.set(p.x,y+3,p.z);world.level.add(glow);}
 }
}

export function deckAt(world,x,z){return (world.walkSurfaces||[]).find(s=>{const dx=x-s.x,dz=z-s.z,co=Math.cos(s.rotation),si=Math.sin(s.rotation);return Math.abs(dx*co-dz*si)<s.width/2&&Math.abs(dx*si+dz*co)<s.length/2;});}
