import {illumination} from './lighting.mjs';
import {buildRegion,regionHeight,waterAt} from './region-world.mjs';
import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
export {THREE};
export class World{
 constructor(canvas){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xb4d9d7);this.camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.15,360);this.camera.position.set(15,13,20);this.hemi=new THREE.HemisphereLight(0xe8ffe8,0x40574b,1.85);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(0xffe3b5,2.5);this.sun.position.set(35,50,25);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:130});this.sun.shadow.bias=-.0003;this.sun.shadow.normalBias=.08;this.scene.add(this.sun,this.sun.target);this.rim=new THREE.DirectionalLight(0xb3e5ff,1.1);this.rim.position.set(-30,15,-20);this.scene.add(this.rim);this.level=new THREE.Group();this.scene.add(this.level);this.actors=new THREE.Group();this.scene.add(this.actors);this.effects=new THREE.Group();this.scene.add(this.effects);this.templates=new Map();this.loader=new GLTFLoader();this.colliders=[];this.interactions=[];this.elapsed=0;this.wind={value:0};this.windShaders=[];this.particles=[];this.rings=[];this.beams=[];this.orbit={yaw:.42,pitch:.61,distance:18};this.cameraTarget=new THREE.Vector3();this.shake=0;this.region='verdant';this.quality='auto';this.fpsSamples=[];this.addSky();window.addEventListener('resize',()=>this.resize());this.resize();}
 resize(){const w=document.documentElement.clientWidth||innerWidth,h=document.documentElement.clientHeight||innerHeight;this.renderer.domElement.style.width='100%';this.renderer.domElement.style.height='100%';this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 addSky(){const g=new THREE.SphereGeometry(220,24,12);const m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x70bccc)},bottom:{value:new THREE.Color(0xcfe5c5)}},vertexShader:'varying vec3 vWorld; void main(){vWorld=(modelMatrix*vec4(position,1.0)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vWorld,1.0);}',fragmentShader:'varying vec3 vWorld; uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp((vWorld.y+20.0)/120.0,0.0,1.0);gl_FragColor=vec4(mix(bottom,top,h),1.0);}' });this.sky=new THREE.Mesh(g,m);this.scene.add(this.sky);}
 height(x,z){return regionHeight(this,x,z);}
 async template(path){if(!this.templates.has(path)){this.templates.set(path,this.loader.loadAsync(new URL(`../assets/environment/${path}.glb`,import.meta.url).href).then(g=>{const obj=g.scene;obj.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(obj);obj.userData.bounds=bounds;obj.traverse(m=>{if(!m.isMesh)return;m.castShadow=true;m.receiveShadow=true;for(const mat of Array.isArray(m.material)?m.material:[m.material]){if(mat.map)mat.map.anisotropy=Math.min(4,this.renderer.capabilities.getMaxAnisotropy());if(path.includes('tent'))mat.color.multiply(new THREE.Color(0xe29953));if(path.includes('campfire'))mat.color.multiply(new THREE.Color(0x62402d));if(/Tree|Grass|Bush|Fern|Flower|Pine|Plant/.test(path)&&!mat.userData.wind){mat.userData.wind=true;mat.onBeforeCompile=shader=>{shader.uniforms.kantoTime=this.wind;shader.vertexShader='uniform float kantoTime;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(kantoTime*1.2 + position.y*.8 + position.x*2.0)*.025*max(0.0,position.y);');};}}});return obj;}));}return this.templates.get(path);}
 shortcutSnapshot(shortcut){if(shortcut.regionId!==this.region||!shortcut.blockerAsset)return [];const path=shortcut.blockerAsset.replace('.glb','');return (this.placementRecords||[]).filter(r=>r.path===path&&Math.hypot(r.p.x-shortcut.interaction[0],r.p.z-shortcut.interaction[1])<5).map(r=>{const matrix=new THREE.Matrix4();r.mesh.getMatrixAt(r.index,matrix);return {...r,matrix};});}
 restoreShortcutPreview(snapshot=[]){for(const r of snapshot){r.mesh.setMatrixAt(r.index,r.matrix);r.mesh.instanceMatrix.needsUpdate=true;r.mesh.computeBoundingSphere();}}
 previewShortcut(s,snapshot,f){for(const r of snapshot){let m;if(s.capability==='strength'&&s.pushTo)m=new THREE.Matrix4().makeTranslation((s.pushTo[0]-r.p.x)*f,0,(s.pushTo[1]-r.p.z)*f).multiply(r.matrix);else{const y=this.height(r.p.x,r.p.z);m=new THREE.Matrix4().makeTranslation(r.p.x,y,r.p.z).multiply(new THREE.Matrix4().makeScale(1-f,1-f,1-f)).multiply(new THREE.Matrix4().makeTranslation(-r.p.x,-y,-r.p.z)).multiply(r.matrix);}r.mesh.setMatrixAt(r.index,m);r.mesh.instanceMatrix.needsUpdate=true;r.mesh.computeBoundingSphere();}}
 clearShortcut(shortcut){if(shortcut.regionId!==this.region||!shortcut.blockerAsset)return;this.clearedShortcuts??=new Set();if(this.clearedShortcuts.has(shortcut.id))return;const snapshot=this.shortcutSnapshot(shortcut),props=new Set(snapshot.map(r=>r.p));this.previewShortcut(shortcut,snapshot,1);if(shortcut.capability==='strength'&&shortcut.pushTo){for(const c of this.colliders)if(props.has(c.prop)){c.x=shortcut.pushTo[0];c.z=shortcut.pushTo[1];}}else this.colliders=this.colliders.filter(c=>!props.has(c.prop));this.clearedShortcuts.add(shortcut.id);}


 owned(mesh){mesh.userData.owned=true;this.level.add(mesh);return mesh;}
 async build(biome,onProgress=()=>{}){if(!this.compositions?.regions[biome.id])throw Error('Missing authored region: '+biome.id);return buildRegion(this,biome,onProgress);}
 isWater(x,z){return !!waterAt(this,x,z);}
 setPickupVisible(key,visible){for(const r of this.placementRecords||[])if(r.p.pickupKey===key){r.originalMatrix??=(()=>{const m=new THREE.Matrix4();r.mesh.getMatrixAt(r.index,m);return m;})();r.mesh.setMatrixAt(r.index,visible?r.originalMatrix:new THREE.Matrix4().makeScale(0,0,0));r.mesh.instanceMatrix.needsUpdate=true;r.mesh.computeBoundingSphere();}}
 syncPickupVisibility(playTime){for(const i of this.interactions)if(i.kind==='pickup'){const visible=!i.usedUntil||i.usedUntil<=playTime;if(i.visualVisible!==visible){this.setPickupVisible(i.key,visible);i.visualVisible=visible;}}}
 addStationSign(x,z,color,kind){const first=this.level.children.length;const y=this.height(x,z)+1.9,material=()=>new THREE.MeshBasicMaterial({color,toneMapped:false});if(kind==='save'){const board=this.owned(new THREE.Mesh(new THREE.BoxGeometry(.72,.85,.12),material()));board.position.set(x,y,z);for(const dy of [-.2,0,.2]){const line=this.owned(new THREE.Mesh(new THREE.BoxGeometry(.44,.07,.14),new THREE.MeshBasicMaterial({color:0x36534f})));line.position.set(x,y+dy,z);}}else if(kind==='heal'){for(const [width,height] of [[.85,.17],[.17,.85]]){const bar=this.owned(new THREE.Mesh(new THREE.BoxGeometry(width,height,.12),material()));bar.position.set(x,y,z);}}else{const sign=this.owned(new THREE.Mesh(kind==='drink'?new THREE.OctahedronGeometry(.34):new THREE.IcosahedronGeometry(.35,0),material()));sign.position.set(x,y,z);}for(const object of this.level.children.slice(first))object.userData.interfaceMarker=true;}
 addBeacon(x,z,color){const ring=this.owned(new THREE.Mesh(new THREE.RingGeometry(.85,1,32),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.5,side:THREE.DoubleSide})));ring.rotation.x=-Math.PI/2;ring.position.set(x,this.height(x,z)+.1,z);ring.userData.beacon=true;ring.userData.interfaceMarker=true;const beam=this.owned(new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,3.2,5),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.4})));beam.position.set(x,this.height(x,z)+1.6,z);beam.userData.interfaceMarker=true;}
 addAtmosphere(random,id){const spec=this.composition?.ambient,n=spec?.count??180,a=new Float32Array(n*3),b=spec?.bounds||[-60,-60,60,60];for(let i=0;i<n;i++){a[i*3]=b[0]+random()*(b[2]-b[0]);a[i*3+1]=(spec?.minY??1)+random()*((spec?.maxY??21)-(spec?.minY??1));a[i*3+2]=b[1]+random()*(b[3]-b[1]);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(a,3));const m=new THREE.PointsMaterial({color:spec?.color||(id==='volcano'?0xffbc6d:id==='ruins'?0xcbb6ff:0xfff4c9),size:spec?.size||(id==='frozen'?.12:.055),transparent:true,opacity:.75,depthWrite:false});this.motes=this.owned(new THREE.Points(g,m));}

 clearLevel(){for(const m of this.ownedMaterials||[])m.dispose();this.ownedMaterials=[];this.composition=null;this.previewMarkersHidden=undefined;this.interiorBlend=undefined;this.dayBlend=undefined;this.cutawayMeshes=[];this.clearedShortcuts=new Set();this.gates=[];this.walkSurfaces=[];this.placementRecords=[];this.encounterFocus=null;this.colliders=[];this.interactions=[];this.water=null;this.fireLight=null;this.level.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.userData.owned){o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}}});this.level.clear();this.clearEffects();}
 clearEffects(){for(const o of [...this.effects.children]){o.geometry?.dispose();o.material?.dispose();}this.effects.clear();this.particles=[];this.rings=[];this.beams=[];}
 collision(x,z,r=.55){const bounds=this.composition?.playableBounds||{min:[-68,-68],max:[68,68]};x=Math.max(bounds.min[0],Math.min(bounds.max[0],x));z=Math.max(bounds.min[1],Math.min(bounds.max[1],z));for(const c of this.colliders){if(c.disabled)continue;if(c.type==='obb'){const co=Math.cos(c.rotation),si=Math.sin(c.rotation),dx=x-c.x,dz=z-c.z;let lx=dx*co-dz*si,lz=dx*si+dz*co;const qx=Math.max(-c.halfWidth,Math.min(c.halfWidth,lx)),qz=Math.max(-c.halfDepth,Math.min(c.halfDepth,lz)),vx=lx-qx,vz=lz-qz,d=Math.hypot(vx,vz);if(d<r){if(d>.001){lx=qx+vx/d*r;lz=qz+vz/d*r;}else if(c.halfWidth-Math.abs(lx)<c.halfDepth-Math.abs(lz))lx=(lx<0?-1:1)*(c.halfWidth+r);else lz=(lz<0?-1:1)*(c.halfDepth+r);x=c.x+lx*co+lz*si;z=c.z-lx*si+lz*co;}continue;}const dx=x-c.x,dz=z-c.z,d=Math.hypot(dx,dz),min=c.r+r;if(d<min){const angle=d>.001?Math.atan2(dz,dx):0;x=c.x+Math.cos(angle)*min;z=c.z+Math.sin(angle)*min;}}return [x,z];}
 burst(position,color,count=20,power=1){const g=new THREE.BufferGeometry(),a=new Float32Array(count*3),v=[];for(let i=0;i<count;i++){v.push(new THREE.Vector3((Math.random()-.5)*5*power,Math.random()*4*power,(Math.random()-.5)*5*power));}g.setAttribute('position',new THREE.BufferAttribute(a,3));const m=new THREE.PointsMaterial({color,size:.12*power,transparent:true,opacity:1,depthWrite:false,blending:THREE.AdditiveBlending});const p=new THREE.Points(g,m);p.position.copy(position);this.effects.add(p);this.particles.push({mesh:p,v,life:.8,max:.8});}
 ring(position,color,radius=3,life=.6){const m=new THREE.Mesh(new THREE.RingGeometry(.8,1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));m.rotation.x=-Math.PI/2;m.position.copy(position);m.position.y+=.08;this.effects.add(m);this.rings.push({mesh:m,life,max:life,radius});return m;}
 beam(from,to,color,width=.15,life=.18,electric=false){if(electric){const pts=[from.clone()];for(let i=1;i<7;i++){const p=from.clone().lerp(to,i/7);p.x+=(Math.random()-.5)*1.1;p.y+=(Math.random()-.5)*.9;p.z+=(Math.random()-.5)*1.1;pts.push(p);}pts.push(to.clone());const curve=new THREE.CatmullRomCurve3(pts);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,20,width,5,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95}));this.effects.add(mesh);this.beams.push({mesh,life,max:life});return mesh;}
 const delta=to.clone().sub(from);const mesh=new THREE.Mesh(new THREE.CylinderGeometry(width,width,delta.length(),8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending}));mesh.position.copy(from).add(to).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());this.effects.add(mesh);this.beams.push({mesh,life,max:life});return mesh;}
 focusEncounter(model,duration=3.5){this.encounterFocus={model,time:duration,duration};}
 updateGates(allowed){for(const gate of this.gates||[]){const open=!gate.spec.pending&&allowed(gate.spec.requirements,gate.spec);gate.mesh.visible=!open;gate.collider.disabled=open;}}
 cameraClearance(origin,offset){const length=offset.length(),horizontal=offset.x*offset.x+offset.z*offset.z;let distance=length;if(horizontal<.01)return length;for(const c of this.colliders){if(c.disabled||!c.h)continue;if(c.type==='obb'){const co=Math.cos(c.rotation),si=Math.sin(c.rotation),dx=origin.x-c.x,dz=origin.z-c.z,starts=[dx*co-dz*si,origin.y,dx*si+dz*co],directions=[offset.x*co-offset.z*si,offset.y,offset.x*si+offset.z*co],mins=[-c.halfWidth-.35,c.bottomY??this.height(c.x,c.z),-c.halfDepth-.35],maxs=[c.halfWidth+.35,c.topY??this.height(c.x,c.z)+c.h,c.halfDepth+.35];let near=0,far=1;for(let a=0;a<3;a++){if(Math.abs(directions[a])<.0001){if(starts[a]<mins[a]||starts[a]>maxs[a])far=-1;}else{const t1=(mins[a]-starts[a])/directions[a],t2=(maxs[a]-starts[a])/directions[a];near=Math.max(near,Math.min(t1,t2));far=Math.min(far,Math.max(t1,t2));}}if(near<=far&&near>0&&near<1)distance=Math.min(distance,Math.max(3.5,near*length-.5));continue;}const t=((c.x-origin.x)*offset.x+(c.z-origin.z)*offset.z)/horizontal;if(t<=0||t>=1)continue;const dx=origin.x+offset.x*t-c.x,dz=origin.z+offset.z*t-c.z,r=c.cameraRadius||c.r;if(dx*dx+dz*dz>r*r)continue;const y=origin.y+offset.y*t;if(y>this.height(c.x,c.z)+c.h+1)continue;distance=Math.min(distance,Math.max(3.5,t*length-r-.5));}return distance;}
 update(dt,target,{mode='field',hour=9,weather='clear',motion=true}={}){this.elapsed+=dt;this.wind.value=this.elapsed;const preview=mode==='starter';if(this.previewMarkersHidden!==preview){for(const object of this.level.children)if(object.userData.interfaceMarker)object.visible=!preview;this.previewMarkersHidden=preview;}const light=illumination(this,dt,target,hour),sheltered=light.inside>.6,snowy=this.region==='highlands'&&target?.x>22&&target?.z< -18;if(this.liquidLight)this.liquidLight.value=light.liquid;this.sun.intensity=light.sun;this.sky.material.uniforms.top.value.set(this.palette?.sky||0xb4d9d7).multiplyScalar(light.sky);this.sky.material.uniforms.bottom.value.set(this.palette?.fog||0xb4d9d7).multiplyScalar(light.fog);if(this.scene.fog)this.scene.fog.color.set(this.palette?.fog||0xb4d9d7).multiplyScalar(light.fog);this.hemi.intensity=light.hemi;if(this.fireLight)this.fireLight.intensity=8+Math.sin(this.elapsed*11)*1.5;if(this.fireLight&&Math.random()<dt*7)this.burst(new THREE.Vector3(1,this.height(1,-5)+.7,-5),0xffb05e,3,.2);
 if(this.motes){this.motes.visible=!sheltered;const a=this.motes.geometry.attributes.position;for(let i=0;i<a.count;i++){a.setX(i,a.getX(i)+Math.sin(this.elapsed*.6+i)*dt*(snowy?.7:.08));a.setY(i,a.getY(i)+(this.composition?.ambient?.velocity!==undefined?dt*this.composition.ambient.velocity:-dt*(weather==='rain'?9:snowy||this.region==='frozen'?.6:.08)));const low=this.composition?.ambient?.minY??0,high=this.composition?.ambient?.maxY??20;if(a.getY(i)<low)a.setY(i,high);if(a.getY(i)>high)a.setY(i,low);}a.needsUpdate=true;this.motes.material.size=this.composition?.ambient?.size|| (weather==='rain'?.07:snowy||this.region==='frozen'?.14:.055);}
 for(const list of [this.particles,this.rings,this.beams])for(let i=list.length-1;i>=0;i--){const p=list[i];p.life-=dt;if(p.life<=0){this.effects.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();list.splice(i,1);continue;}p.mesh.material.opacity=p.life/p.max;if(p.v){const a=p.mesh.geometry.attributes.position;p.v.forEach((v,j)=>{a.setXYZ(j,a.getX(j)+v.x*dt,a.getY(j)+v.y*dt,a.getZ(j)+v.z*dt);v.y-=dt*5;});a.needsUpdate=true;}else if(p.radius)p.mesh.scale.setScalar(p.radius*(1-p.life/p.max)+.1);}
 // Scenery only shortens the camera arm; targeting never changes the player's view.
 if(target){const desired=target.clone().add(new THREE.Vector3(0,Math.max(1.1,(this.playerHeight||2)*.5),0));if(mode==='title'){desired.set(1,1,-1);this.orbit.yaw=.48+Math.sin(this.elapsed*.08)*.05;this.orbit.distance=23;this.orbit.pitch=.47;}let yaw=this.orbit.yaw,pitch=this.orbit.pitch,d=Math.max(this.orbit.distance,Math.min(27,(this.playerHeight||2)*3.2+12));if(mode==='starter'&&this.starterFocus){const model=this.starterFocus;this.starterFrame??=new THREE.Box3().setFromObject(model);const box=this.starterFrame,size=box.getSize(new THREE.Vector3()),stage=document.querySelector('#starter-preview')?.getBoundingClientRect(),w=this.renderer.domElement.clientWidth,h=this.renderer.domElement.clientHeight,available=stage?.height||h*.45,center=stage?stage.top+stage.height/2:h*.43;desired.copy(box.getCenter(new THREE.Vector3()));yaw=.08;pitch=.08;const halfTan=Math.tan(this.camera.fov*Math.PI/360);d=Math.max(size.y/(2*halfTan*(available/h)),Math.max(size.x,size.z)/(2*halfTan*this.camera.aspect*.7))*1.34;this.camera.setViewOffset(w,h,0,h/2-center,w,h);}else if(this.camera.view?.enabled)this.camera.clearViewOffset();const focus=this.encounterFocus;if(focus&&focus.model.parent&&mode==='field'){focus.time-=dt;desired.copy(focus.model.position).add(new THREE.Vector3(0,(focus.model.userData.height||3)*.45,0));yaw+=.65*(1-focus.time/focus.duration);pitch=.3;d=Math.max(9,(focus.model.userData.height||3)*2.1);if(focus.time<=0)this.encounterFocus=null;}this.cameraTarget.lerp(desired,1-Math.exp(-dt*6));const offset=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*d,Math.sin(pitch)*d,Math.cos(yaw)*Math.cos(pitch)*d);let clearance=mode==='starter'?d:this.cameraClearance(this.cameraTarget,offset);offset.setLength(Math.min(d,Math.max(3.5,clearance)));const cameraPos=this.cameraTarget.clone().add(offset);if(mode!=='starter')cameraPos.y=Math.max(cameraPos.y,this.height(cameraPos.x,cameraPos.z)+3);this.camera.position.lerp(cameraPos,1-Math.exp(-dt*9));if(motion&&this.shake>0){this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;}if(motion&&this.impulse){this.camera.position.add(this.impulse);this.impulse.multiplyScalar(Math.exp(-dt*25));}this.camera.lookAt(this.cameraTarget);this.sun.target.position.copy(target);this.sun.position.copy(target).add(new THREE.Vector3(35,50,25));}this.shake=Math.max(0,this.shake-dt*2);}
 highlightInteraction(i){if(!this.interactionMarker?.parent){this.interactionMarker=this.owned(new THREE.Mesh(new THREE.RingGeometry(.8,.86,40),new THREE.MeshBasicMaterial({color:0xffe3a1,transparent:true,opacity:.6,side:THREE.DoubleSide,depthWrite:false,toneMapped:false})));this.interactionMarker.rotation.x=-Math.PI/2;}this.interactionMarker.visible=!!i;if(i)this.interactionMarker.position.set(i.x,this.height(i.x,i.z)+.13,i.z);}
 render(){this.renderer.render(this.scene,this.camera);}
 project(v){const p=v.clone().project(this.camera);return {x:(p.x*.5+.5)*innerWidth,y:(-.5*p.y+.5)*innerHeight,visible:p.z<1&&p.z>-1&&Math.abs(p.x)<1.1&&Math.abs(p.y)<1.1};}
 setQuality(q){this.quality=q;const high=q==='high',low=q==='low';this.renderer.setPixelRatio(low?1:Math.min(devicePixelRatio,high?2:1.5));this.renderer.shadowMap.enabled=true;const size=low?512:2048;if(this.sun.shadow.mapSize.x!==size){this.sun.shadow.mapSize.set(size,size);this.sun.shadow.map?.dispose();this.sun.shadow.map=null;}this.resize();}
}
