import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {MergeGame,VERSION,verifyReplay} from '../games/jigglypuff/engine.mjs';
import {LocalDB} from './volleyball-local-db.mjs';
import {signJwt} from '../functions/_shared/jwt.js';
import {onRequestGet,onRequestPost} from '../functions/api/games/jigglypuff.js';
function replay(seed,mode='endless',idle=0){const game=new MergeGame(seed,mode),drops=[];for(let n=0;!game.over&&n<100000;n++){if(game.ticks%65===0&&game.drop([240,100,360,180,300][Math.floor(game.ticks/65)%5]))drops.push([game.ticks,[240,100,360,180,300][Math.floor(game.ticks/65)%5]]);game.step();game.events.length=0;}assert(game.over);const trace={version:VERSION,ticks:game.ticks+idle,drops:drops.map(([t,x])=>[t+idle,x])};return trace;}
const speed=new MergeGame(1,'speed');speed.balls=[speed.make(6,230,450),speed.make(6,230,320)];speed.step();assert(speed.won&&speed.over);assert.equal(speed.points,640);
const endless=new MergeGame(1,'endless');endless.balls=[endless.make(6,230,450),endless.make(6,230,320)];endless.step();assert(!endless.won&&!endless.over);assert.equal(endless.maxLevel,7);endless.balls=[endless.make(7,240,430),endless.make(7,240,269)];endless.step();assert.equal(endless.balls.length,0);assert.equal(endless.points,1920);assert(!endless.over);assert(endless.drop(240),'continues after clearing Jigglypuffs');
const calm=new MergeGame(1);calm.drop(0);assert.equal(calm.balls[0].x,45);assert(!calm.drop(200));for(let n=0;n<21601;n++)calm.step();assert(!calm.over&&calm.asleep);assert(calm.drop(480));assert.equal(calm.balls.at(-1).x,435);
let winningCase,failedCase;for(let seed=1;seed<=50&&(!winningCase||!failedCase);seed++){const trace=replay(seed,'speed'),result=verifyReplay(seed,trace,'speed');if(result.won)winningCase={seed,trace,result};else failedCase={seed,trace,result};}assert(winningCase&&failedCase,'deterministic completed and failed fixtures');
const trace=replay(11),result=verifyReplay(11,trace,'endless');assert(result.durationMs>0);assert.throws(()=>verifyReplay(11,{...trace,ticks:trace.ticks-1},'endless'));assert.throws(()=>verifyReplay(11,{...trace,drops:[[0,240],[1,240]]},'endless'));assert.throws(()=>verifyReplay(11,{...trace,drops:[]},'endless'));assert.throws(()=>verifyReplay(11,{...trace,ticks:Number.MAX_SAFE_INTEGER+1},'endless'));
const twoHours=2*60*60*120,longTrace=replay(11,'endless',twoHours);assert.equal(verifyReplay(11,longTrace,'endless').durationMs,result.durationMs+7200000);
const DB=new LocalDB();DB.sqlite.exec('CREATE TABLE users(id TEXT PRIMARY KEY,name TEXT)');const schema=readFileSync(new URL('../functions/_schema/jigglypuff_modes.sql',import.meta.url),'utf8');DB.sqlite.exec(schema);DB.sqlite.exec(schema);for(const id of ['alice','bob'])DB.prepare('INSERT INTO users VALUES(?,?)').bind(id,id+'@private.test').run();
const env={DB,JWT_SECRET:'isolated-test-only'},tokens={};for(const id of ['alice','bob'])tokens[id]=await signJwt({sub:id,email:id+'@private.test',exp:Math.floor(Date.now()/1000)+3600},env.JWT_SECRET);
const url='https://tcghub.test/api/games/jigglypuff';
async function post(data,user='alice',headers={}){const response=await onRequestPost({request:new Request(url,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://tcghub.test',...(user?{Cookie:'session='+tokens[user]}:{}),...headers},body:JSON.stringify(data)}),env});return{status:response.status,data:await response.json()};}
async function get(mode='endless',user='alice'){const response=await onRequestGet({request:new Request(url+'?mode='+mode,{headers:user?{Cookie:'session='+tokens[user]}:{}}),env});return response.json();}
const start={action:'start',mode:'endless',nickname:'시험 닉네임',version:VERSION};assert.equal((await get()).rows.length,0);assert.equal((await post(start,null)).status,401);assert.equal((await post(start,'alice',{Origin:'https://other.test'})).status,403);assert.equal((await post({...start,nickname:'<script>'})).status,400);assert.equal((await post({...start,mode:'wrong'})).status,400);
const started=await post(start);assert.equal(started.status,200);assert.equal((await post(start)).status,429);const rankedReplay=replay(started.data.seed),verified=verifyReplay(started.data.seed,rankedReplay,'endless'),finish={action:'finish',sessionId:started.data.sessionId,replay:rankedReplay,score:999999,mode:'speed'};
assert.equal((await post(finish,'bob')).status,409);assert.equal((await post(finish)).status,400);DB.prepare('UPDATE jigglypuff_mode_sessions SET started_at=? WHERE user_id=?').bind(Date.now()-verified.durationMs-100,'alice').run();const saved=await post(finish);assert.equal(saved.status,200);assert(saved.data.ranked);assert.equal(saved.data.score,verified.score);assert((await post(finish)).data.alreadySaved);assert.equal((await get('speed')).rows.length,0,'submitted mode cannot move an endless session into speed ranking');assert.equal((await get()).mine.rank,1);
DB.prepare('INSERT INTO jigglypuff_mode_records VALUES(?,?,?,?,?,?,?,?)').bind('bob','endless','밥',verified.score,verified.maxLevel,0,Math.max(1,verified.durationMs-10),1).run();assert.equal((await get()).mine.rank,2);assert.equal((await get()).rows[0].nickname,'밥');
for(const [id,score,time] of [['alice',99999,90000],['bob',640,80000]])DB.prepare('INSERT INTO jigglypuff_mode_records VALUES(?,?,?,?,?,?,?,?)').bind(id,'speed',id,score,7,1,time,1).run();assert.equal((await get('speed')).rows[0].nickname,'bob','speed sorts by completion time, not points');assert.equal((await get('speed')).mine.rank,2);assert.equal((await get()).rows[0].nickname,'밥','mode boards are independent');
assert.throws(()=>DB.prepare('INSERT OR REPLACE INTO jigglypuff_mode_records VALUES(?,?,?,?,?,?,?,?)').bind('bob','speed','invalid',50,2,0,100,1).run(),'failed speed runs cannot enter ranking');
DB.prepare('DELETE FROM jigglypuff_mode_records WHERE mode=?').bind('speed').run();DB.prepare('UPDATE jigglypuff_mode_sessions SET started_at=0').run();const failedStart=await post({...start,mode:'speed'});DB.prepare('UPDATE jigglypuff_mode_sessions SET seed=? WHERE user_id=?').bind(failedCase.seed,'alice').run();const failedTrace=failedCase.trace,failedResult=failedCase.result;assert(!failedResult.won);DB.prepare('UPDATE jigglypuff_mode_sessions SET started_at=? WHERE user_id=?').bind(Date.now()-failedResult.durationMs-100,'alice').run();const failedSave=await post({action:'finish',sessionId:failedStart.data.sessionId,replay:failedTrace});assert.equal(failedSave.status,200);assert.equal(failedSave.data.ranked,false);assert.equal((await get('speed')).rows.length,0);assert.equal((await get()).rows.length,2);
DB.prepare('UPDATE jigglypuff_mode_sessions SET started_at=0').run();const longStart=await post(start);DB.prepare('UPDATE jigglypuff_mode_sessions SET seed=?,started_at=? WHERE user_id=?').bind(11,Date.now()-result.durationMs-7200100,'alice').run();assert.equal((await post({action:'finish',sessionId:longStart.data.sessionId,replay:longTrace})).status,200);
for(const waitTicks of [1200,0,2400]){DB.prepare('UPDATE jigglypuff_mode_sessions SET started_at=0').run();const started=await post({...start,mode:'speed'});const trace={...winningCase.trace,ticks:winningCase.trace.ticks+waitTicks,drops:winningCase.trace.drops.map(([t,x])=>[t+waitTicks,x])};DB.prepare('UPDATE jigglypuff_mode_sessions SET seed=?,started_at=? WHERE user_id=?').bind(winningCase.seed,Date.now()-trace.ticks*1000/120-100,'alice').run();const saved=await post({action:'finish',sessionId:started.data.sessionId,replay:trace});assert.equal(saved.status,200);assert(saved.data.ranked);assert.equal((await get('speed')).mine.duration_ms,winningCase.result.durationMs+(waitTicks===1200?10000:0),'speed personal best improves only for faster completions');}
const listing=await get();assert(!JSON.stringify(listing).includes('user_id'));assert(!JSON.stringify(listing).includes('@private'));assert.equal((await get('endless',null)).mine,null);DB.prepare('DELETE FROM users WHERE id=?').bind('bob').run();assert.equal(DB.prepare('SELECT COUNT(*) AS n FROM jigglypuff_mode_records WHERE user_id=?').bind('bob').first().n,0);DB.sqlite.close();
console.log('PASS: speed completion, endless continuation/Jigglypuff clear, cooldown, unlimited time, deterministic/long replay, SQLite mode separation and sorting, failed-speed exclusion, auth/ownership/origin, trusted session mode, idempotency, privacy and account deletion.');
