const assert=require('node:assert/strict');
const fs=require('node:fs');
const {rows,series,pct,paginate}=require('../assets/portfolio-screen.js');
const many=Array.from({length:28},(_,id)=>({id}));
assert.equal(paginate(many,1).items.length,10);
assert.equal(paginate(many,2).items[0].id,10);
assert.equal(paginate(many,3).items.length,8);
assert.equal(paginate(many,100).page,3);
assert.equal(paginate(many.slice(0,10),3).page,1);
assert.deepEqual(paginate([],3).items,[]);
assert.equal(paginate(many,-1).page,1);
const holdings=[{id:1,card_id:'1',grade:'psa10',qty:2,buy_price:100},{id:2,card_id:'2',grade:'raw',qty:1,buy_price:200}];
const cache={'1':{latestPrices:{psa10:120},history:[{date:'2026-09-01',psa10_price:100},{date:'2026-09-03',psa10_price:120}]},'2':{latestPrices:{raw:150},history:[{date:'2026-09-02',raw_price:200},{date:'2026-09-03',raw_price:150}]}};
const r=rows(holdings,cache);assert.equal(r[0].value,240);assert.equal(r[1].itemPnl,-50);assert.equal(r[1].itemPct,-25);assert(pct(-25).startsWith('▼ -'));assert(pct(25).startsWith('▲ +'));
assert.deepEqual(series(holdings,cache,30,10,Date.parse('2026-09-03T12:00:00Z')),[{date:'2026-09-02',value:4000},{date:'2026-09-03',value:3900}]);
assert.deepEqual(series(holdings,cache,1,10,Date.parse('2026-09-03T12:00:00Z')),[{date:'2026-09-03',value:3900}]);
assert.deepEqual(series(holdings,{},30,10),[]);
assert.equal(rows([{card_id:'1',grade:'psa10',qty:1,buy_price:0}],{})[0].itemPct,null);
assert.equal(rows([{card_id:'1',grade:'psa10',qty:1,buy_price:100}],{'1':{latestPrices:{psa10:0}}})[0].value,0,'zero quote is not replaced by cost');
assert.equal(rows(holdings,cache,new Set(['1']))[0].grade,'box','existing box ID classification');
assert.equal(rows(holdings,cache)[0].grade,'psa10','pack text never classifies cards as boxes');
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('portfolio-screen.js'));assert(html.includes('admin-account-entry'));assert(html.includes('registerPsaCert'));assert(html.includes('registerBgsCert'));assert(html.includes('removeWatchlistApi'));
console.log('PASS: portfolio totals, negative/zero/missing quotes, box classification, sparse history forward fill, date ranges, existing actions');
