const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const ctx={window:{openSetGrid(){}},renderCardInfo(){},document:{getElementById(){return null},addEventListener(){}},fetch:()=>new Promise(()=>{})};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'assets/english-catalog.js'),'utf8'),ctx);
const api=ctx.window.EnglishCatalog;
const sample=[{date:'2026-09-01',priceCents:10000},{date:'2026-09-01',priceCents:12000},{date:'2026-09-10',priceCents:20000}];
const rows=JSON.parse(JSON.stringify(api.dailySales(sample)));
assert.equal(rows.length,2);assert.equal(rows[0].price,11000);assert.equal(rows.reduce((n,r)=>n+r.count,0),3);
assert(!rows.some(r=>r.date==='2026-09-02'),'Missing days must not be created as zero volume');
assert.match(api.historyHTML([]),/수집된 PSA10 판매 기록이 없습니다/);
assert.match(api.historyHTML(sample),/\$110\.00/);
assert(!/NaN|Infinity/.test(api.historyHTML([sample[0]])));
assert.equal(api.quote({psa10:{language:'ja',grade:'PSA 10',currency:'JPY',sourcePriceCents:49500}}),'PSA10 미수집');
const file=JSON.parse(fs.readFileSync(path.join(root,'data/english-sets/EN-TCG11803.json'),'utf8'));
const card=file.cards.find(c=>c.number==='116/086');
assert.equal(card.name,'Mega Greninja ex');assert.equal(card.psa10.sourcePriceCents,49500);assert.equal(card.psa10.sales.length,29);
assert.equal(api.dailySales(card.psa10.sales).reduce((n,r)=>n+r.count,0),29);
assert.match(api.art(card),/width:500%;height:400%/);
console.log('PASS: USD prices, partial daily sale counts, missing dates, original card identity and sprite bounds');
