import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const elements={};
for(const id of ['homeAssetValue','homeAssetChange','homeAssetHoldCount','homeAssetWatchCount']) elements[id]={style:{},textContent:''};
const ctx=vm.createContext({document:{getElementById:id=>elements[id]},syncHomeAuthView(){},CURRENT_USER:{id:'unit-test'},HOLDINGS:[],WATCHLIST:[],_PF_PRICE_CACHE:{},BOX_ID_SET:new Set(),JPY_KRW:10});
vm.runInContext(html.slice(html.indexOf('async function renderHomeAsset()'),html.indexOf('window.openPortfolioOrLogin =')),ctx);
await vm.runInContext('renderHomeAsset()',ctx);
assert.equal(elements.homeAssetValue.textContent,'₩0');
ctx.HOLDINGS=[{card_id:'test',grade:'raw',buy_price:100,qty:2}];
ctx.WATCHLIST=[{id:'test-watch'}];
ctx._PF_PRICE_CACHE.test={latestPrices:{raw:150}};
await vm.runInContext('renderHomeAsset()',ctx);
assert.equal(elements.homeAssetValue.textContent,'₩3,000');
assert.equal(elements.homeAssetHoldCount.textContent,'1종');
assert.equal(elements.homeAssetWatchCount.textContent,'1종');
assert.match(elements.homeAssetChange.textContent,/▲ \+₩1,000/);
ctx._PF_PRICE_CACHE.test.latestPrices.raw=50;
await vm.runInContext('renderHomeAsset()',ctx);
assert.match(elements.homeAssetChange.textContent,/▼ -₩1,000/);
ctx.CURRENT_USER=null;
await vm.runInContext('renderHomeAsset()',ctx);
assert.equal(elements.homeAssetValue.textContent,'로그인 필요');
assert.match(html,/body\.home-signed-in:has\(\.home-v3\.active\)/);
assert.match(html,/HUB_NEWS_ITEMS\.slice\(0,4\)/);
assert.match(html,/변동 정보 없음/);
elements.mobileHomeNews={textContent:'',innerHTML:''};
ctx.loadNews=async()=>{};
ctx.HUB_NEWS_ITEMS=JSON.parse(readFileSync(new URL('../data/news.json',import.meta.url),'utf8')).items;
ctx.escapeHtml=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
vm.runInContext(html.slice(html.indexOf('let MOBILE_HOME_NEWS_LOADING ='),html.indexOf("window.matchMedia('(max-width:480px)').addEventListener")),ctx);
await vm.runInContext('loadMobileHomeNews()',ctx);
assert.equal((elements.mobileHomeNews.innerHTML.match(/<a href=/g)||[]).length,4);
assert.match(elements.mobileHomeNews.innerHTML,/원피스/);
assert.match(elements.mobileHomeNews.innerHTML,/mo-news-thumb onepiece/);
console.log(JSON.stringify({ok:true,emptyAssets:true,positiveAndNegative:true,loggedOut:true,realNews:true}));
